### ISSUE TITLE
OWASP Cipher Vulnerabilities

### ISSUE THREAD

**Issue by aligneddev** [aspnet/KestrelHttpServer#1018]
I have a non-standard setup (self signed cert, no IIS to avoid that dependency in this small app that will run on a local network, but we want to encrypt the traffic), but according to [Rapid 7s Nexpose](https://www.rapid7.com/products/nexpose/compare-downloads.jsp), I need to disable support for RC4 ciphers, not support Cipher Block Chaining, and "Configure the server to disable support for static key cipher suites."
3.2.3. TLS/SSL Server Supports RC4 Cipher Algorithms (CVE-2013-2566) (rc4-cve-2013-2566)
"Configure the server to disable support for RC4 ciphers.
For Microsoft IIS web servers, see Microsoft Knowledgebase article 245030 for instructions on disabling rc4 ciphers."

3.3.1. TLS/SSL Server Supports Cipher Block Chaining (CBC) Ciphers (ssl-cbc-ciphers)
"Configure the server to favor GCM over CBC regardless of the cipher size. In other words, use Authenticated Encryption with Associated Data (AEAD), e.g. AES-GCM, AES-CCM."

3.3.2. TLS/SSL Server Supports The Use of Static Key Ciphers (ssl-static-key-ciphers)
"The server is configured to support ciphers known as static key ciphers. These ciphers don't support "Forward Secrecy". In the new specification for HTTP/2, these ciphers have been blacklisted."
"Configure the server to disable support for static key cipher suites."

I also should make sure that TLSv1.2 is being used.

Is there a way in Kestrel or the Asp.Net Core Startup middleware to configure these security settings?
this may be what makes me install the full IIS with this app.

``` c#
var host = new WebHostBuilder()
.UseUrls("http://*:80", "https://*:443")
.UseKestrel(options =>
{
    options.NoDelay = true;
    options.UseHttps(testCertPath, configuration["pfxPassword"]);
    options.UseConnectionLogging();
})
.UseContentRoot(Directory.GetCurrentDirectory())
.UseStartup<Startup>()
.Build();
host.Run();;
```

**Comment by Tratcher** [comment]
Kestrel is not currently qualified for edge deployment, you should be using IIS already.

**Comment by benaadams** [comment]
Says it isn't edge
> this small app that will run on a local network, but we want to encrypt the traffic

@logankd its uses to OS algos so is the same disable process e.g.
http://www.howtogeek.com/221080/how-to-update-your-windows-server-cipher-suite-for-better-security/

**Comment by Tratcher** [comment]
It's strange to pay so much attention to TLS security but disregard the HTTP server security.

**Comment by benaadams** [comment]
A worry of observation vs interference. For example if you were communicating on private network however, you were hosted by a 3rd party you may not be worried about being DoS'd but you may worry about (or have a requirement to prevent) a different 3rd party eavesdropping. DoS is more detectable... :wink:

**Comment by halter73** [comment]
> I also should make sure that TLSv1.2 is being used.

Something like the following should work:

    .UseKestrel(options =>
    {
        options.NoDelay = true;
        options.UseHttps(new HttpsConnectionFilterOptions {
            ServerCertificate = new X509Certificate2(testCertPath, password),
            SslProtocols = SslProtocols.Tls12 });
        options.UseConnectionLogging();
    })

As far as the Cipher options go, Kestrel uses `SslStream` which uses Schannel on Windows. While I haven't tried this personally, I've read this can be configured globally via [some Windows registry keys](https://msdn.microsoft.com/en-us/library/ms925716.aspx).

**Comment by logankd** [comment]
Here's some background of how I got here:

 * It will be installed a computer in the local network enabling configuration without RDP into that box. This is deployed through an installer file.
 *  Asp.Net Core was my choice earlier on, thinking that installing full blown IIS could be avoided. I've been learning more that this isn't the best idea. However, I thought that since it was in a local network it would be ok.
 * Later in the project a username and password login was added to the requirements. I added it with Asp.Net Identity.
 * Then I mentioned that those cred would be passed in the clear from the browser (the user will be on the network, just a different computer) to the computer. "We should encrypt that" came the reply and I agreed :).
  * I created a self-signed cert and added the UseHttps option ([article from that learning](https://gooroo.io/GoorooTHINK/Article/16767/Https-Redirect-with-AspNet-Core-RC2-And-Kestrel-on-Windows/22784)).
 * a couple weeks later came the PEN test (which I didn't think about before or know that was a concern). So now I get to handle these, hence the question.

Thank you!

**Comment by blowdart** [comment]
Cipher suites are selected by the OS, not the web server. So the instructions for IIS would work for Kestrel. There is nothing Kestrel can do to override the cipher suites Windows uses.

Having said that we always say that Kestrel is always run behind IIS, or another forwarding proxy, so ...

**Comment by GuardRex** [comment]
Here are some helpful references, too:

https://www.nartac.com/Products/IISCrypto
https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by logankd** [comment]
@halter73 Thank you for the code. I'm looking into the other links given above. 
@GuardRex I'll suggest the IISCrypto tool to the Ops guys setting up the computer image.

**Comment by benaadams** [comment]
@blowdart not recommending it :smile:

**Comment by logankd** [comment]
@halter73 What is the default value for SslProtocols? I would think that it should be Tls1.2 (+ in the future) so that things are more secure by default. The older options wouldn't be needed (there is probably some use case, but why would someone chose to use the lower?).  

https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Microsoft.AspNetCore.Server.KestrelTests/HttpsConnectionFilterTests.cs didn't point me to what is default.

**Comment by halter73** [comment]
[TLS 1.1 + TLS 1.2](https://github.com/aspnet/KestrelHttpServer/blob/1.0.0/src/Microsoft.AspNetCore.Server.Kestrel.Https/HttpsConnectionFilterOptions.cs#L16) is the current default.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by kdaveid** [comment]
Since kestrel is edge-ready, this is related to #1865
