### ISSUE TITLE
Get NullReferenceException when running kestrel for a while

### ISSUE THREAD

**Issue by cnblogs-dudu** [aspnet/KestrelHttpServer#115]
```
# dnx . kestrel
Started

Unhandled Exception: System.NullReferenceException: 
Object reference not set to an instance of an object.
at Microsoft.AspNet.Server.Kestrel.Networking.UvShutdownReq.UvShutdownCb(IntPtr ptr, Int32 status)

# dnx . kestrel
Started
```

**Comment by Tragetaschen** [comment]
#63

**Comment by shhsu** [comment]
I have actually gotten a similar issue

**Comment by lodejard** [comment]
It sounds like the period of time that the async shutdown is "active" needs to be guarded by a gchandle as well. Same as the uvwritereq - handle created when operation begins and freed in the callback.

**Comment by shhsu** [comment]
The reproduction of this problem is simple.
* Build and run HelloMvc app with coreclr on linux (I used Ubuntu)
* Hit the index page with some load test (I used WCat)
Kestrel should crash pretty fast (10~20 seconds)

Note: I seem to be getting similar trouble with Kestrel on coreclr on Windows as well. After hitting HelloMvc on Kestrel on Windows the dnx process would become unresponsive. I will be debugging it.
