### ISSUE TITLE
Question: How does Libuv compare with SocketAsyncEventArgs?

### ISSUE THREAD

**Issue by Lothy** [aspnet/KestrelHttpServer#1201]
Hi everyone,

I know you've done a lot of work to achieve some rather ambitious performance targets. I'm just wondering if anyone could provide insight into just how efficient native C# SocketAsyncEventArgs is (or can be) compared to Libuv.

Is anyone willing to share insight into this, particularly with respect to jitter/latency and garbage collector pressure?

What are/were the drivers for wrapping Libuv instead of other approaches? Is it because SocketAsyncEventArgs wasn't available in dotnet core at some point, or reasoning along similar lines?

Thank you for taking the time to read this.

**Comment by cesarbs** [comment]
> What are/were the drivers for wrapping Libuv instead of other approaches? Is it because SocketAsyncEventArgs wasn't available in dotnet core at some point, or reasoning along similar lines?

That's correct.

I did a quick experiment several months ago where I replaced libuv with async socket calls using `SocketAsyncEventArgs`. I ran our plaintext benchmark and there didn't seem to be any performance hit there. It was a very buggy experiment though, something I dedicated only a couple of hours to, just to see if we could at some point remove the dependency on libuv.

It's not exactly a trivial change because with libuv we can assume certain things in the code - namely that we know which thread we are in when running any libuv callback, and that those callbacks are run sequentially in the event loop. With `SocketAsyncEventArgs` this changes because the callbacks can be scheduled on any thread and there are no guarantees regarding ordering or concurrency.

We might revisit this again in the future, but it's not a priority right now.

**Comment by Lothy** [comment]
Yeah, I was playing with some `SocketAsyncEventArgs` code in the debugger and saw that it farms work out to a 'Worker Thread' (which I'm sure comes from the default thread pool).
I'm not sure if there's a way to control this process - nothing stood out in the API.

Insights around the internet, particular in the FIX protocol space, suggest that the optimal approach to networking is a single-thread performing all socket-related work. The thread is pinned to a particular CPU core.
This thread then acts as a producer for one or more consumer threads that execute business logic.

It sounds like using Libuv is more accommodating of this approach.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
