### ISSUE TITLE
SSL Issues

### ISSUE THREAD

**Issue by Serjster** [aspnet/KestrelHttpServer#1348]
I am continually frustrated with running SSL in my apps. I have to keep trying different ports until finally one works (yes, I am using the Enable SSL checkbox in the web app properties to get different ports.) I keep getting this error:

> An error occurred attempting to determine the process id of dotnet.exe which is hosting your application. One or more errors occurred.

![image](https://cloud.githubusercontent.com/assets/3606218/22714287/10cddda2-ed49-11e6-9e95-a1660a9085ef.png)

I do have my localhost certificate dragged to the Trusted Root Certification Authorities:
![image](https://cloud.githubusercontent.com/assets/3606218/22714373/63b74bde-ed49-11e6-9f19-c4fb461cd300.png)

I've restarted VS, rebooted PC and none of those help. This is a really frustrating issue. 

Using:
Windows 10 Pro x64, Version 1607, Build 14393.693
Intel i7-3930 
64 GB RAM
VS 2015 Version 14.0.25431.01 Update 3

Project:
`"Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    }
  },
  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  }`

**Comment by halter73** [comment]
@Tratcher Any idea what's going on here? It seems like it might be an ANCM issue.

**Comment by Tratcher** [comment]
@pan-wang @shirhatti

**Comment by pan-wang** [comment]
it seems to be a VS tooling issue. @jhkimnew who may have experience with ANCM inside VS.

**Comment by jhkimnew** [comment]
@Serjster 
I am sorry but I don't know what causes the problem. 

I tried to reproduce the error message you reported here with some possible repro condition such as removing certificate or using duplicated tcp port which is used by other program but I was not able to find the repro steps. So, I think you should narrow down the issue or find the repro steps. Because you told that only specific tcp port works on your machine, there should be a reason why other tcp port does not work. 
If you open the launchSettings.json which is under "Properties\PublishProfiles" of your project, you can change the TCP port manually and you can find which tcp port is causing the problem on your machine and you will need to find why those tcp port does not work.

BTW, I'd like to clarify one thing. You told that you dragged your localhost certificate to the Trusted Root Certification Authorities. Do you mean you *move*, not copy, the certificate, right? 
If so, that will cause another problem and you will need to move back to the original location.
 
Some more detailed information for you:
IISExpress uses predefined certificate mapping for 100 tcp ports from 44300 to 43399.
The localhost certificate is bound for all the 100 tcp ports and the location of the certificate is hard-coded such as the Personal folder. If you move the certificate to other place, it will work temporarily because http service uses cached certificate but it won't work when the cached certificate is gone, which happens when you reboot the machine or restart http service.

**Comment by jhkimnew** [comment]
@Serjster 
FYI, 
The same error was reported from this issue which seems to happen only after upgrading VS. 
Is https://github.com/aspnet/Home/issues/1608.

Is your problem related to the issue?

**Comment by Serjster** [comment]
@jhkimnew The "dragging" issue was the problem. I dragged it back to Personal, exported from there, imported into Trusted and next time I tried running VS with SSL, I got a pop up in my VS asking if I want to trust my cert... I said yes... and now it's working again. Thanks for the free education and sorry for wasting your time.
