### ISSUE TITLE
Migrate output to use Pipe

### ISSUE THREAD

**Issue by pakrym** [aspnet/KestrelHttpServer#1475]

**Comment by davidfowl** [comment]
Here are my random notes having spiked this before:
- There are inefficiencies around getting memory out of the writable buffer over and over
- The codegen needs to be changed for header writing
- Socket shutdown needs to be handled differently (probably with a cancel pending read)
- synchronous writes and flushes are tricky (since we don't have a way to wait in pipelines)

**Comment by aL3891** [comment]
Its gonna be really interesting to try this with https://github.com/aL3891/PipelineSerialization :)

**Comment by davidfowl** [comment]
This is done
