### ISSUE TITLE
Content-Length on HEAD requests

### ISSUE THREAD

**Issue by jchannon** [aspnet/KestrelHttpServer#1680]
On HEAD requests Kestrel doesn't return the `"Transfer-Encoding: chunked"` header as there is no body however if a body is returned Kestrel rightly doesn't output that body but I think it should set a `Content-Length` header.

**Comment by muratg** [comment]
Assigning to @natemcmaster for investigation.

**Comment by natemcmaster** [comment]
Closing as wontfix. Per the spec on HTTP/1.1.

> The HEAD method is identical to GET except that the server MUST NOT
   send a message body in the response

https://tools.ietf.org/html/rfc7231#section-4.3.2

This includes preserving any Content-Length headers set by the application so that clients can get metadata about what would happen if they issue a GET. Kestrel shouldn't set the `Content-Length` header as this would violate the requirement that HEAD be identical to GET without the body.
