### ISSUE TITLE
Filter before HTTPS on Full framework seems to break kestrel

### ISSUE THREAD

**Issue by Drawaes** [aspnet/KestrelHttpServer#1711]
ASP.NET 1.1.1

https://github.com/Drawaes/FullFrameBrokenVsCore/tree/master

In that project you can see a "pass through" stream (this is not the actual use case but is simplified to show the issue at hand).

If you use the flag in the project (UseHttps) and run with netcoreapp1.1 it works fine. If you turn off Https using that flag it works in 461 and Netcoreapp1.1.

However if that flag is on in 461 you never get the last "chunk" of the request.

Any ideas why this would be this is causing issues in prod.

Cheers

**Comment by Drawaes** [comment]
I know there are tests for logging connection filter before/after https. This isn't a known issue for the full framework is it?

**Comment by muratg** [comment]
cc @halter73

**Comment by halter73** [comment]
This scenario works on full framework given the right pass through Stream. We test it [here](https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/LoggingConnectionAdapterTests.cs#L18). I think you're running into an issue because BackToBackStream doesn't implement the [APM methods that LogginStream does](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel.Core/Adapter/Internal/LoggingStream.cs#L135).

**Comment by Drawaes** [comment]
Bingo, that works thanks a bunch!
