### ISSUE TITLE
Consider reverting back to a non-throwing way of shutting down the connection

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1819]
In https://github.com/aspnet/KestrelHttpServer/commit/c48113ad805a53bc98a999a7004b6bb13763bf25 we changed a call to `CancelPendingRead()` to `Complete(new ConnectionAbortedException())`, while this made the pattern more consistent it also throws a bunch more first chance exceptions. We could go back to CancelPendingRead instead.

/cc @pakrym @halter73

**Comment by halter73** [comment]
What's the purpose of ever calling `IPipeWriter.Complete(Exception)` instead of `IPipeWriter.Complete()`? The OutputConsumer handles an exception and a normal completed read the exact same way. The ConnectionAbortedException isn't even logged.

As an aside, maybe we should consider not [calling Frame.Abort() every time the connection is closed by the client](https://github.com/aspnet/KestrelHttpServer/commit/c48113ad805a53bc98a999a7004b6bb13763bf25#diff-c29d4223e14a61ba892bd186d5d2f3f5R123). We would still have to trip the RequestAborted token like we are considering for 1.x.x, but we don't necessarily need to kill the connection immediately with an error.

**Comment by davidfowl** [comment]
#1820
