### ISSUE TITLE
[Patch 1.0.5] Error -16 EBUSY resource busy or locked

### ISSUE THREAD

**Issue by muratg** [aspnet/KestrelHttpServer#1910]
Details at https://github.com/aspnet/KestrelHttpServer/issues/1909.  Fix already exists in dev/2.0.0.

**Comment by muratg** [comment]
cc @Eilon @shirhatti Patch candidate (1.1.3)

**Comment by Eilon** [comment]
This patch is *approved* for 1.0.x. Please follow the patch creation instructions that were sent by email, and submit a PR to the correct branch.

**Comment by cesarbs** [comment]
This doesn't seem to repro on 1.0.x. The test added in #1633 failed on 1.1.x before I applied the patch, but not on 1.0.x. Should we still proceed with the patch?

**Comment by cesarbs** [comment]
cc @halter73 @davidfowl

**Comment by cesarbs** [comment]
I also tried a manual repro but couldn't make it crash.

**Comment by cesarbs** [comment]
The shutdown logic in 1.0.x is very different from 1.1.x (the latter is better, in 1.0.x things are kind of all over the place). I'm wondering if changing the 1.0.x shutdown to be like 1.1.x will repro the issue, which can then be fixed (my worry is that the bug is there in 1.0.x. but is much more subtle). But that would turn this change into a much larger one than originally intended.

**Comment by cesarbs** [comment]
I believe I figured out why the bug doesn't repro in 1.0.x.

In Kestrel 1.1.x, the shutdown sequence that starts in `KestrelThread.StopAsync` calls `ConnectionManager.WalkConnectionsAndCloseAsync`, which walks all stream handles in the uv loop and attempts to close all connections associated with those. It then calls `KestrelThread.AllowStop`, which unreferences the async handle, allowing the uv loop to exit. The bug repros when the loop exits but there are still inactive handles in it. In that case, we see the EBUSY error when attempting to dispose the loop. The walk introduced in #1798 fixes that by making sure all handles are disposed before disposing the loop.

In Kestrel 1.0.x though, we still do the walk in `ConnectionManager` when disposing listeners, but then `KestrelThread.Stop` always calls `KestrelThread.OnStopRude`, which walks *all* handles in the uv loop and disposes them, and finally disposes the async handle. This allows the uv loop to exit, and since all handles are now disposed, an EBUSY never happens.

We don't need this patch in 1.0.x.

**Comment by muratg** [comment]
Thanks @cesarbs!  

Closing this one.

**Comment by Eilon** [comment]
Ok I removed from the OneNote and I'm closing this bug.
