### ISSUE TITLE
How will rate limit take into account something like TLS?

### ISSUE THREAD

**Issue by Drawaes** [aspnet/KestrelHttpServer#1984]
If there is a rate limit of say 1k per 5 seconds, TLS could require 16k before it can pass down the frame to Kestrel. Therefore Kestrel may assume that the client is not sending any data for 16 seconds and kill it but the client maybe sending at the correct rate. On a mobile connection this could be an issue. 

My question is really, is it possible (or does it already) count data at the socket or does it count data that gets through the "pipe" to kestrel?

**Comment by cesarbs** [comment]
The data rate is not measured at the socket level. The reason for that is that we only measure the data rate for the request body, but not for the headers, meaning you have to know something about the request in order to start measuring the rate.

Have you done any experiments that demonstrate there is an issue when using TLS? I think ultimately you could set the rate low enough that it wouldn't abort connections where the TLS layer is buffering data before sending it up to Kestrel.Core, but there would indeed be a mismatch between the rate at which the client is sending data and what Kestrel is seeing.

**Comment by Drawaes** [comment]
I could do some but I am not that worried about it being an issue... is there some docs somewhere that I could add a note to something like

"Please note that the rate is measured at the http parsing level, therefore any large headers or filters on the raw traffic (TLS for instance) will potentially effect the measurements"

??

I think the behaviour is fine just should be documented?

**Comment by cesarbs** [comment]
@danroth27 Can we add this to our docs?

**Comment by Drawaes** [comment]
Was this added ? Or will it be I would like to close out the issue.

**Comment by cesarbs** [comment]
Pinging @danroth27 again.

**Comment by danroth27** [comment]
@Drawaes Could you please add an issue to https://github.com/aspnet/docs with what you want added to the docs?
