### ISSUE TITLE
How to use custom domains with Kestler on a dev machine

### ISSUE THREAD

**Issue by mahdi** [aspnet/KestrelHttpServer#1997]
Is it possible to use custom domains (e.g.: http://mydomain.dev) instead of http://localhost:XXXXX in Kestler. Something like this in IIS and ASP.NET MVC 4: [https://stackoverflow.com/a/21407121/27946](https://stackoverflow.com/a/21407121/27946)

P.S. I'm using Visual Studio for Mac and ASP.NET Core 1.1.

**Comment by natemcmaster** [comment]
Kestrel doesn't bind to specific domains, only network interfaces on the machine. Our docs contain examples of how to bind to a public IP address instead of localhost (aka loopback). In 1.1, this is usually done by calling `.UseUrls("http://+:80")` on WebHostBuilder.

See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel for more details.

**Comment by mahdi** [comment]
Thank you @natemcmaster! Do you recommend any solution to have a custom domain while working on a development machine (either Windows or Mac)?

**Comment by davidfowl** [comment]
Edit the hosts file

**Comment by mahdi** [comment]
@davidfowl I know that, but can we bind Kestler to e.g. http://127.0.0.1:1234 and map it to http://mydomain.dev?

**Comment by davidfowl** [comment]
You can't bind to anything besides port 80 and 443 with the hosts file. You'd need something else in front of your application (like IIS) routing based on the host header.

**Comment by mahdi** [comment]
@davidfowl It works with IIS on Windows. What do you recommend on a Mac machine?

**Comment by davidfowl** [comment]
IIS does the routing, that's why it works. On a MAC, use nginx, see https://stackoverflow.com/questions/10729034/can-i-map-a-hostname-and-a-port-with-etc-hosts for samples on how you could configure nginx to do this.

Alternatively, if you're feeling lucky, you could do something crazy like:

Kestrel (port:80) -> Kestrel (port:1234)

You'd also need to write a piece of middleware that proxies requests to the back end process based on the host header matching.

**Comment by mahdi** [comment]
Thanks @davidfowl, will give it a try 👍

**Comment by Tratcher** [comment]
I thought the hosts file only hijacked DNS, the port should be unrelated.

**Comment by davidfowl** [comment]
@mahdi 

> I thought the hosts file only hijacked DNS, the port should be unrelated.

I guess I wasn't clear. If you want to map http://mydomain.dev:1234 to to http://127.0.0.1:1234 then the host file is all you need. If you want to map http://mydomain.dev:80 to http://127.0.0.1:1234 then what i said is what you need.
