### ISSUE TITLE
Not closing connections and FIN with status -107

### ISSUE THREAD

**Issue by indikaudagedara** [aspnet/KestrelHttpServer#2002]
While doing a load test on an AspNet.Core 1.0 application running on Ubuntu 16.04 behind nginx I noticed # of connections opening (pattern `Connection id.*started` in the logs) but not all of them are closing (pattern `Connection id.*stopped` in the logs) - at the same time I started seeing db connections breaking. This is what prompted me to look at the connection open/close as only one of the load balanced servers showed the errors and all others were fine and queries traced in server were all running fine.

I'm putting here the steps I followed to check the connections opened and closed within a period
```
$ egrep ' 06:.*Connection.*stop' *0817*| egrep -o ' 06:[34].' | uniq -c > /tmp/l.stop
$ egrep ' 06:.*Connection.*started' *0817*| egrep -o ' 06:[34].' | uniq -c > /tmp/l.start
$ paste /tmp/l.start /tmp/l.stop
    ##opening##     ##closing##
    246  06:30      246  06:30
    233  06:31      232  06:31
    156  06:32      157  06:32
    210  06:33      210  06:33
    189  06:34      188  06:34
    175  06:35      175  06:35
    183  06:36      183  06:36
    195  06:37      196  06:37
    139  06:38       18  06:38 <-- only 18/139 got closed within the minute
    128  06:39       82  06:39
    122  06:40      269  06:40
    135  06:41      135  06:41
      1  06:42        1  06:42
     11  06:44       11  06:44
     46  06:45       46  06:45
     91  06:46       91  06:46
    122  06:47      122  06:47
    175  06:48      175  06:48
    163  06:49      163  06:49
``` 

Now, analyzing the connections around 06:38, which is the period that shows fewer connections closing, I see the following (from the above logs around 18 connections closed out of 139 opened)
```
$ grep ' 06:38.*Connection.*id.*start' *0817* | head -30 | cat -n
    # log line
     1  2017-08-17 06:38:01.202 [] [DBG] Connection id ""0HL755RKGJDTQ"" started.
     2  2017-08-17 06:38:01.299 [] [DBG] Connection id ""0HL755RKGJDTR"" started.
     3  2017-08-17 06:38:01.432 [] [DBG] Connection id ""0HL755RKGJDTS"" started.
     4  2017-08-17 06:38:01.537 [] [DBG] Connection id ""0HL755RKGJDTT"" started.
     5  2017-08-17 06:38:02.101 [] [DBG] Connection id ""0HL755RKGJDTU"" started.
     6  2017-08-17 06:38:02.743 [] [DBG] Connection id ""0HL755RKGJDTV"" started.
     7  2017-08-17 06:38:02.912 [] [DBG] Connection id ""0HL755RKGJDU0"" started.
     8  2017-08-17 06:38:02.923 [] [DBG] Connection id ""0HL755RKGJDU1"" started.
     9  2017-08-17 06:38:03.128 [] [DBG] Connection id ""0HL755RKGJDU2"" started.
    10  2017-08-17 06:38:03.408 [] [DBG] Connection id ""0HL755RKGJDU3"" started.
    11  2017-08-17 06:38:03.660 [] [DBG] Connection id ""0HL755RKGJDU4"" started.
    12  2017-08-17 06:38:03.679 [] [DBG] Connection id ""0HL755RKGJDU5"" started.
    13  2017-08-17 06:38:03.927 [] [DBG] Connection id ""0HL755RKGJDU6"" started.
    14  2017-08-17 06:38:04.121 [] [DBG] Connection id ""0HL755RKGJDU7"" started.
    15  2017-08-17 06:38:04.470 [] [DBG] Connection id ""0HL755RKGJDU8"" started.
    16  2017-08-17 06:38:04.686 [] [DBG] Connection id ""0HL755RKGJDU9"" started.
    17  2017-08-17 06:38:04.981 [] [DBG] Connection id ""0HL755RKGJDUA"" started.
    18  2017-08-17 06:38:05.352 [] [DBG] Connection id ""0HL755RKGJDUB"" started.
    19  2017-08-17 06:38:09.743 [] [DBG] Connection id ""0HL757A3BLMA3"" started.
    20  2017-08-17 06:38:09.952 [] [DBG] Connection id ""0HL757A3BLMA4"" started.
    21  2017-08-17 06:38:10.219 [] [DBG] Connection id ""0HL757A3BLMA5"" started.
    22  2017-08-17 06:38:11.254 [] [DBG] Connection id ""0HL757A3BLMA6"" started.
    23  2017-08-17 06:38:12.380 [] [DBG] Connection id ""0HL757A3BLMA7"" started.
    24  2017-08-17 06:38:12.657 [] [DBG] Connection id ""0HL757A3BLMA8"" started.
    25  2017-08-17 06:38:13.175 [] [DBG] Connection id ""0HL757A3BLMA9"" started.
    26  2017-08-17 06:38:13.512 [] [DBG] Connection id ""0HL757A3BLMAA"" started.
    27  2017-08-17 06:38:13.594 [] [DBG] Connection id ""0HL757A3BLMAB"" started.
    28  2017-08-17 06:38:13.705 [] [DBG] Connection id ""0HL757A3BLMAC"" started.
    29  2017-08-17 06:38:14.077 [] [DBG] Connection id ""0HL757A3BLMAD"" started.
    30  2017-08-17 06:38:14.212 [] [DBG] Connection id ""0HL757A3BLMAE"" started.
```

So looking at one of the closed ones (started and closed within 47ms)
```
$ grep 0HL755RKGJDTQ *0817*
2017-08-17 06:38:01.202 [] [DBG] Connection id ""0HL755RKGJDTQ"" started.
2017-08-17 06:38:01.246 [0HL755RKHO8D3] [DBG] Connection id ""0HL755RKGJDTQ"" completed keep alive response.
2017-08-17 06:38:01.246 [] [DBG] Connection id ""0HL755RKGJDTQ"" received FIN.
2017-08-17 06:38:01.247 [] [DBG] Connection id ""0HL755RKGJDTQ"" disconnecting.
2017-08-17 06:38:01.247 [] [DBG] Connection id ""0HL755RKGJDTQ"" sending FIN.
2017-08-17 06:38:01.247 [] [DBG] Connection id ""0HL755RKGJDTQ"" sent FIN with status "0".
2017-08-17 06:38:01.247 [] [DBG] Connection id ""0HL755RKGJDTQ"" stopped.
```

And one of the not closed ones below. This took 2 minutes from the `started` and `stopped` log lines and **importantly**, logs `sent FIN with status "-107"` compared to ` sent FIN with status "0"`
```
$ grep 0HL757A3BLMA3 *0817*
2017-08-17 06:38:09.743 [] [DBG] Connection id ""0HL757A3BLMA3"" started.
2017-08-17 06:38:29.726 [] [DBG] Connection id ""0HL757A3BLMA3"" received FIN.
2017-08-17 06:40:01.456 [0HL757A3CPVM5] [DBG] Connection id ""0HL757A3BLMA3"" completed keep alive response.
2017-08-17 06:40:01.456 [] [DBG] Connection id ""0HL757A3BLMA3"" disconnecting.
2017-08-17 06:40:01.456 [] [DBG] Connection id ""0HL757A3BLMA3"" sending FIN.
2017-08-17 06:40:01.456 [] [DBG] Connection id ""0HL757A3BLMA3"" sent FIN with status "-107".
2017-08-17 06:40:01.456 [] [DBG] Connection id ""0HL757A3BLMA3"" stopped.
```

Now I understand this is a pretty specific question and may difficult to follow. And my questions are: 
- Does the status -107 and the tcp connection taking 2 minutes indicate a problem of Kestrel server or is it receiving too many requests (this is running on a 2 CPU/ 4 GB t2.medium EC2 instance on AWS)?
- And why do I see connection open/close happening within ~40ms (according to the logs above). Could it have something to do with how nginx is reverse proxying to Kestrel?

**Comment by halter73** [comment]
Can you explain what this has to do with db connections breaking? I don't see how that's related.

The -107 status uppon sending a TCP FIN typically means that the client disconnected prior to the server's attempt to gracefully close the connection. The 107 status means ENOTCONN (Transport endpoint is not connected) comes from [errno.h](https://github.com/torvalds/linux/blob/99f781b1bfc199ec8eb86d4e015920faf79d5d57/include/uapi/asm-generic/errno.h#L89) and libuv flips it to a negative value to make it clear that it's an error.

In this case, the "received FIN" log indicates that the client did indeed attempt to close the connection gracefully about 20 seconds after the connection started.

The problem is that prior to 2.0, Kestrel probably took the TCP spec too literally and interpreted a FIN from the client to mean that the client simply wouldn't send more data but would still receive more data, so Kestrel would not immediately send a [FIN, ACK]. Instead it would wait for the ASP.NET request delegate to complete prior to potentially sending a FIN.

If you look at your other logs just prior to the 06:40:01.456 mark, I expect you'll see a log like "Request finished in [over a minute]ms [HTTP status] [Content-Type]". Unfortunately this log doesn't include the connection id.

After this long running request completed about a minute and a half after the client sent the FIN, Kestrel finally attempts to send the FIN. At this point, the OS notifies Kestrel that the client already disconnected a while ago with the 107 error code which Kestrel logs with a fairly low level of importance (Debug).

I can't tell you why the only connection only lived for ~40ms other than to say that the "completed keep alive response" log indicates that one request/response was completed in that time period. Once again the client initiated the FIN, but in that case Kestrel sent back it's a [FIN, ACK] immediately because the request delegate had already completed unlike in the ~2 minute case.

In 2.0.0, Kestrel always interprets a FIN from the client as an attempt to abort the connection *immediately* even if the request delegate is still running and will promptly send back a [FIN, ACK] no matter what.

**Comment by indikaudagedara** [comment]
Thanks @halter73 

> Can you explain what this has to do with db connections breaking? I don't see how that's related.

This is actually what I'm trying to find out. DB connection breaking is the symptom I'm investigating. For some reason the connections start to break in one server (have multiple servers running the same application in a load balanced env). I see everything else normal - network, cpu, memory all fine - no network connectivity failure and can see packets in/out in the same rates across all servers. The only abnormality I see (in the problem server) is the connection open/close discrepancy. Hence thought the DB connectivity failure had something to do with the Kestrel connection open/close (eg. too many connections causing some problem or another).

**Comment by halter73** [comment]
It's possible that the cause and effect are reversed. If the db connections are failing after a timeout, it's possible that that explains the long-running request and in turn the -107 status.
