### ISSUE TITLE
RequestStream does not support length property even when Content-Length is set on the request

### ISSUE THREAD

**Issue by buraktamturk** [aspnet/KestrelHttpServer#2059]
Hello,

The stream implementation that can be found in Request.Body does not suport Length and Position properties even when Content-Length header is set on the request. There are numerous libraries that depends on these properties. 

**For example,** Amazon S3 does not support chunked uploads (like Azure do!) and the client library looks for remaining Stream size (Length - Position) to set "Content-Length" header to the file upload request. Also, Amazon's library does not allow the size to be specified explicitly.  

```csharp
// this does not work just because the library don't know the length of the given stream
await s3.PutObjectAsync(new Amazon.S3.Model.PutObjectRequest {
	BucketName = "blablabla",
	InputStream = Request.Body,
	ContentType = Request.ContentType,
	Key = file.id + "/" + fileName,
// no property to set the length of the InputStream
});
```

To make it work one can copy the Request.Body stream to a new MemoryStream and use this stream to make file upload request. However, this is inefficent and would waste a lot of memory.

I have implement a proxy class that implements Length property based on Content-Length header and tracks the length of the data that have been readed before as position (the latter is not implemented yet) to work around the issue https://paste.sh/0pTxO9JI#KqSZwgjvMm28ySc6AAOoLQhv

```csharp
InputStream = new LengthStream(Request.Body, Request.ContentLength.Value),
```

I hope it gets implemented in the future so my projects (and projects of other .NET developers) would look more cleaner without these workarounds.

**Comment by Tratcher** [comment]
By design. On the Stream API Length, Position, CanSeek, a Seek are all interrelated. https://msdn.microsoft.com/en-us/library/system.io.stream.canseek(v=vs.110).aspx The Stream contract only supports these for random access streams. The request and response streams are not random access streams, they are linear consumption streams.

 Consumers that require random access need to enable buffering. The EnableRewind extension can be used to help enable this. https://github.com/aspnet/HttpAbstractions/blob/87cd79d6fc54bb4abf07c1e380cd7a9498a78612/src/Microsoft.AspNetCore.Http/Internal/BufferingHelper.cs#L41

**Comment by buraktamturk** [comment]
@Tratcher there are libraries that use Length and Position property without looking seekability on the Stream (Amazon S3 does not check whatever the stream is seekable or not). Enabling buffering just for this case would still waste resources (either on disk or memory). Length can be the value of the "Content-Length" header if present, Position can be a read only counter that counts how much data has been transfered on Read calls in the past.

However, if it is against of the rules of the .NET world, feel free to close the issue.
