### ISSUE TITLE
RFC 8187 - Character Encoding for Headers

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#2063]
Hot off the presses (September 2017) https://tools.ietf.org/html/rfc8187

Indicating Character Encoding and Language for HTTP Header Field Parameters

/cc @Tratcher @blowdart @halter73

**Comment by Tratcher** [comment]
Hmm, interesting choices. It only applies to key value pairs within headers, and is ASCII compatible, so I don't foresee making any changes to Kestrel. Microsoft.Net.Http.Headers in HttpAbstractions looks like the most obvious consumer/producer of such values. ContentDispositionHeaderValue already supports this because it was designed for use in multipart MIME bodies: https://github.com/aspnet/HttpAbstractions/blob/5128efe0e88eaa176d4231ff62d754de59bb0edd/src/Microsoft.Net.Http.Headers/ContentDispositionHeaderValue.cs#L347

Move to HttpAbstractions?

**Comment by benaadams** [comment]
Moved https://github.com/aspnet/HttpAbstractions/issues/940
