### ISSUE TITLE
Server returning `RequestTimeout` if the request stream is not read

### ISSUE THREAD

**Issue by markvincze** [aspnet/KestrelHttpServer#2095]
If I implement a very simple ASP.NET Server, which returns a hardcoded dummy response without reading the request, and send a couple of larger (a couple kbytes) requests to it, the server responds to the second request with a `RequestTimeout` instead of `OK`. It only happens on Linux, it works properly on Windows.

I uploaded a self-contained repro here: https://github.com/markvincze/KestrelRequestTimeout

The test works properly on Windows, but it fails on Linux (I tested with Ubuntu, and also with Docker on Windows).

Does this seem to be a bug, or am I doing something wrong in my code?

(I've seen [this issue](https://github.com/dotnet/corefx/issues/17330), which seems to be similar, but that's supposed to be fixed in 2.0.)

**Comment by halter73** [comment]
@markvincze Thanks for the awesome repro. It made it very easy to track down the issue. I captured a network trace using wireshark, and it looks like there is a bug in the Linux HttpClient.

In your repro, Kestrel is sending a 200 response without sending a "HTTP/1.1 100 Continue" response or waiting for the first request body to even start uploading. This itself is not a bug, but this is what triggers the HttpClient issue.

At this point, HttpClient should either upload the first request body before reusing the TCP connection for new requests or simply close the TCP connection. Instead, HttpClient on Linux is attempting to immediately send the following request without ever sending the 7000 byte response body for the first request.

Kestrel interprets this "new request" as the body of the first request. The bytes and the very end of the the "new request" are interpreted as the beginning (i.e. start line) of the second request. Since Kestrel never technically receives a complete second request, it eventually times out and sends a 408 response.

![image](https://user-images.githubusercontent.com/54385/31205225-0a2da638-a925-11e7-925c-079039d83aa5.png)

**Comment by markvincze** [comment]
Hi @halter73,
Thanks for picking this up!

And thanks @lucaslorentz for investigating the [original issue](https://github.com/markvincze/Stubbery/pull/5).

**Comment by halter73** [comment]
No problem. At least you can work around the issue for now by explicitly consuming the request body.
