### ISSUE TITLE
The connection was closed because the response was not read by the client at the specified minimum data rate

### ISSUE THREAD

**Issue by desmondgc** [aspnet/KestrelHttpServer#2171]
After upgrading to ASP.NET Core 2.0, I've been encountering the MinResponseDataRate limit sporadically for a certain controller action that returns a ~30 MB response. I am able to work around the issue by disabling the limit, but it's not clear to me why the limit is being hit.

Timeline:

```
11:28:28.992 - Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response.
11:28:28.992 - Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
11:28:37.153 - Connection id "0HL9DJ6TCCU64", Request id "0HL9DJ6TCCU64:00000001": the connection was closed becuase the response was not read by the client at the specified minimum data rate.
11:28:37.153 - Connection id "0HL9DJ6TCCU64" disconnecting.
11:28:37.153 - Connection id "0HL9DJ6TCCU64" communication error.
```

My scenario is very similar to the one described in [this Stack Overflow thread](https://stackoverflow.com/questions/46584760/connection-was-closed-error-between-httpclient-and-asp-net-core-2-0-webservice).

From what I can tell, the client is in the process of downloading the response at a reasonable rate when the connection is closed, but it's hard to troubleshoot because it happens intermittently. I'm basically looking for guidance on how to troubleshoot this issue.

**Comment by halter73** [comment]
Have you read the "Minimum request body data rate" section in [the Kestrel doc](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?tabs=aspnetcore2x#how-to-use-kestrel-in-aspnet-core-apps) linked to in the Stack Overflow thread? I realize you're dealing with the minimum *response* data rate, but that section covers both requests and responses.

It demonstrates how to globally reconfigure `options.Limits.MinResponseDataRate`. It also shows how to reconfigure the minimum rate per request. Ex:

```c#
context.Features.Get<IHttpMinResponseDataRateFeature>()
    .MinDataRate = new MinDataRate(bytesPerSecond: 100, gracePeriod: TimeSpan.FromSeconds(10));
```

As the doc mentions, "The default minimum rate is 240 bytes/second, with a 5 second grace period." If you have some evidence that Kestrel is killing connections with a higher transfer rate, I'm interested to see it.

**Comment by melnikov77** [comment]
I have a similar problem, under high load, some of the connections are aborted because of rate limit.
With default settings, I have an aborted connection after 5 seconds (i.e grace period ) while writing 130Kb chunk.
I think the problem could be in OutputProducer.WriteAsync method.
I added some logs to this method (see code below), here is what happened when the connection is aborted:

1. OutputProducer:WriteAsync - writing 131072
2. OutputProducer:WriteAsync - BytesWritten after commit - 0
3. OutputProducer:FlushAsyncAwaited -StartTimingWrite - 0
3.1  2017-12-15 21:43:30.892 Microsoft.AspNetCore.Server.Kestrel Connection id ""0HLA40JF02TB4"", Request id ""0HLA40JF02TB4:00000001"": the connection was closed becuase the response was not read by the client at the specified minimum data rate.
3.2 2017-12-15 21:43:30.892 Microsoft.AspNetCore.Server.Kestrel Connection id ""0HLA40JF02TB4"" disconnecting.
4. OutputProducer:FlushAsyncAwaited - IsCancellationRequested - True

So it looks like:
1. WritableBuffer has been changed/purged between (1) and (2).
2. StartTimingWrite is called with 0 bytes instead of 131072, i.e. monitor thread thinks we are writing 0 bytes
3. Libuv thread is sending 131072 bytes, i.e. it going to take some time
3. Monitor thread aborts connection after 5 seconds (grace period) instead of 546 seconds (131072 / 240, 240 is default rate)

`

namespace Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http {
    
    class OutputProducer 
    {

    // other code is omitted


         private Task WriteAsync(
            ArraySegment<byte> buffer,
            CancellationToken cancellationToken,
            bool chunk = false)
        {
            _log.LogDebug($"OutputProducer:WriteAsync - writing {buffer.Count}");

            var writableBuffer = default(WritableBuffer);

            lock (_contextLock)
            {
                if (_completed)
                {
                    return Task.CompletedTask;
                }

                writableBuffer = _pipe.Writer.Alloc(1);
                var writer = new WritableBufferWriter(writableBuffer);
                if (buffer.Count > 0)
                {
                    if (chunk)
                    {
                        ChunkWriter.WriteBeginChunkBytes(ref writer, buffer.Count);
                    }

                    writer.Write(buffer.Array, buffer.Offset, buffer.Count);

                    if (chunk)
                    {

                        ChunkWriter.WriteEndChunkBytes(ref writer);
                    }
                }

                writableBuffer.Commit();
               _log.LogDebug($"OutputProducer:WriteAsync - BytesWritten after commit - {writableBuffer.BytesWritten}");
            }

            return FlushAsync(writableBuffer, cancellationToken);
        }

        private async Task FlushAsyncAwaited(WritableBufferAwaitable awaitable, int count, CancellationToken cancellationToken)
        {
            // https://github.com/dotnet/corefxlab/issues/1334
            // Since the flush awaitable doesn't currently support multiple awaiters
            // we need to use a task to track the callbacks.
            // All awaiters get the same task
            lock (_flushLock)
            {
                if (_flushTcs == null || _flushTcs.Task.IsCompleted)
                {
                    _flushTcs = new TaskCompletionSource<object>();

                    awaitable.OnCompleted(_flushCompleted);
                }
            }

           _log.LogDebug($"OutputProducer:FlushAsyncAwaited - StartTimingWrite - {count}");

            _timeoutControl.StartTimingWrite(count);
            await _flushTcs.Task;
            _timeoutControl.StopTimingWrite();

            _log.LogDebug($"OutputProducer:FlushAsyncAwaited - IsCancellationRequested - {cancellationToken.IsCancellationRequested}");

            cancellationToken.ThrowIfCancellationRequested();
        }
    }
}
`

**Comment by halter73** [comment]
@melnikov77 Thanks for the thorough investigation. We are working now on rewriting the write timeout logic to avoid this kind of issue and others. In the meantime I recommend disabling the response rate limit for problematic requests and add your own timeout logic that aborts the connection if necessary.

**Comment by davidfowl** [comment]
@muratg why did you move this to discussions?  @halter73 this seems like a bug no?

**Comment by muratg** [comment]
@davidfowl Original post on the issue was a a guidance question. Removing from the milestone to bring it back to triage with @melnikov77's points.

**Comment by muratg** [comment]
What's the current costing on this?

**Comment by muratg** [comment]
Closing this one.
