### ISSUE TITLE
Cultures Not Working with ASP.Net Core 2.0

### ISSUE THREAD

**Issue by dexterhussain** [aspnet/KestrelHttpServer#2208]
I have been working with ASP.Net cultures for a long time and also working on Core 1.0 . Deployed many websites on kestrel using Nginx having no issues. This is first time that I added cultures to my website which are working fine on development machine as soon I deploy it on my Ubuntu Server it starts giving these errors
common.js:22 GET http://(IP)api/culture/SupportedCultures 500 (Internal Server Error)

the server is not sending any of the api calls.
The server starts properly on port 5000.

Content root path: /home/pgc/publish
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

Nginx has most basic configuration just forwarding packets to the backend.
I am unable to sort any issues. Please help if anyone knows.

**Comment by benaadams** [comment]
Can you turn some logging on? It should give you some more insight

**Comment by dexterhussain** [comment]
I cannot log anything as it shows nothing it just starts showing that Internal Server Error
![image](https://user-images.githubusercontent.com/8198511/33645667-c67664e6-da6d-11e7-9ab8-37cecb88866e.png)

**Comment by benaadams** [comment]
Logging in aspnet not in the client; it should output what the issue is

**Comment by benaadams** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x

**Comment by dexterhussain** [comment]
Even though i have enabled logging the Kestrel is still not showing any logs.
It is quite strange this time that kestrel is showing nothing whenever I deployed an application previously it always showed api calls and everything

**Comment by dexterhussain** [comment]
No matter how much calls are coming it doesnt move other than this.
root@sqanercore:~# sudo journalctl -fu kestrel-cms360.service
-- Logs begin at Wed 2017-12-06 16:06:19 PKT. --
Dec 06 17:35:01 sqanercore systemd[1]: [/etc/systemd/system/kestrel-cms360.service:8] Failed to parse sec value, ignoring: 10  # Restart service after 10 seconds if dotnet service crashes
Dec 06 17:35:22 sqanercore systemd[1]: Started CMS360.
Dec 06 17:35:30 sqanercore dotnet-example[4131]: Hosting environment: Production
Dec 06 17:35:30 sqanercore dotnet-example[4131]: Content root path: /var/aspnetcore/publish
Dec 06 17:35:30 sqanercore dotnet-example[4131]: Now listening on: http://localhost:5000
Dec 06 17:35:30 sqanercore dotnet-example[4131]: Application started. Press Ctrl+C to shut down.

**Comment by halter73** [comment]
@dexterhussain The logs in your last comment are really just [the console output from hosting](https://github.com/aspnet/Hosting/blob/a63932a492513cdeb4935661145084cad2ae5521/src/Microsoft.Extensions.Hosting/Internal/ConsoleLifetime.cs#L35-L37) which is always written unless explicitly disabled.

To capture logs written using ASP.NET Core's logging API, you need to [add a logging provider](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#how-to-add-providers). I would use the console logging provider since you're already capturing stdout with systemd.

Once you add a logging provider you should see logs [like this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#sample-logging-output).

You can [increase the verbosity of the logs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#log-filtering). I recommend collecting all logs which would be a "Trace" minimum log level until you figure out the cause of the issue.

**Comment by dexterhussain** [comment]
Dear @halter73  I have already added Logging Provider and even catching and showing each exception but still it is nothing, I simply cannot figure out what is the issue. In all previous application it worked perfectly fine.

**Comment by muratg** [comment]
@dexterhussain Were you able to figure out server logging?

**Comment by dexterhussain** [comment]
Yes I fixed it. The loggin directory needed to be setup

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
