### ISSUE TITLE
TaskCanceledException while reading HttpRequest body content

### ISSUE THREAD

**Issue by gthuruv** [aspnet/KestrelHttpServer#2256]
We see task cancellations while trying to copy the request body content. We do not specify a token to be monitored anywhere in the Request pipeline. The code to read the request content is,

`await _httpContext.Request.Body.CopyToAsync(_contentStream);`

The error we see,

`System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OSIsoft.Data.Server.Http.HttpMessage.<TryUnpack>d__21.MoveNext()`

TryUnpack has the code to copy content from the request body. This is not reproducible on our machines, but we see that happen frequently on our test servers.

**Comment by Tratcher** [comment]
What do Kestrel's logs say when this happens?

**Comment by gthuruv** [comment]
How do we get the Kestrel's logs? Do we have to enable them somewhere?

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#how-to-add-providers

**Comment by gthuruv** [comment]
Hello, Sorry about the delayed response. We were finally able to get some logs from the kestrel. This is what we see around the time we noticed the issue. But it is still hard to correlate these logs with the actual issue.

warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/22/2018 23:46:08 +00:00".
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/22/2018 23:46:11 +00:00".

But a possibly good thing is, we caught this in the debugger and noticed some request aborted property set to true and also the request body's cancellation property triggering cancellation. Here are some pictures,

![image](https://user-images.githubusercontent.com/7110817/35250814-54589c7c-ff8d-11e7-8b7c-a83110042e2b.png)

![image](https://user-images.githubusercontent.com/7110817/35250855-7af5079e-ff8d-11e7-8127-7fa3d725630b.png)

We believe that this happened due to client side timeout after which there was an attempt to read from the request body content. Is there any way this can be confirmed? And if it is indeed a client time out, can we assume the reverse to be true, that task cancellation while reading body content means a client timeout?, because we do not specify any of our cancellation in here.

Thanks.

**Comment by halter73** [comment]
Do you see the heartbeat warnings when the debugger *isn't* attached? If not, it's probably the application being paused under the debugger that's triggering those heartbeat warnings. This will be [fixed in 2.1](https://github.com/aspnet/KestrelHttpServer/pull/2258).

In general, when diagnosing cancellation/timeout issues, I wouldn't use a debugger at all and instead rely entirely on logging or perhaps analyzing memory dumps if necessary.

I see there being two likely possibilities:

1. Clients are sometimes disconnecting on its own mid-request-body upload. In this case, the server is behaving as expected. In this case you should see debug-level logs like "Connection id {ConnectionId} reset.", "Connection id {ConnectionId} communication error.", or even something as benign as ""Connection id {ConnectionId} stopped."
2. Clients are sometimes uploading below the default 240 bytes/second min request body data rate, so Kestrel kills the connection. If that's the case, you should see an information-level log like "Connection id {ConnectionId}, Request id {TraceIdentifier}: the request timed out because it was not sent by the client at a minimum of 240 bytes/second."

**Comment by gthuruv** [comment]
I do see those warnings even when the debugger is not attached.

We are hoping client-timeout is the case. If I remember correctly, we usually see a "Connection error" with a "closed message" in the past, but "TaskCanceledException" is new. Fyi, we did upgrade our kestrel package, Microsoft.AspNetCore.Server.Kestrel, recently from 1.1.2 to 2.0.1.

**Comment by halter73** [comment]
If you are seeing the heartbeat warnings without an attached debugger, you are almost certainly experiencing threadpool starvation. The best way to identify this is to capture a memory dump during the time period you're seeing the heartbeat warnings, and the to analyze the dump using VS's "Parallel Stacks" window.

I describe how to do this in a little more detail in [this comment](https://github.com/aspnet/IISIntegration/issues/245#issuecomment-253668589).

**Comment by gthuruv** [comment]
That is interesting because we are indeed trying to track down a threadpool starvation issue in our application. So this is a side-effect of the true problem, I guess. Thanks for that link. Very useful.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
