### ISSUE TITLE
Bind to IPv6 loopback address when the "localhost" is specified

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#231]
Currently Kestrel only binds to the IPv4 loopback address (127.0.0.1) and not the IPv6 loopback address (::1) when localhost is specified.

#98

**Comment by Tratcher** [comment]
Also for host names and *, bind to IPv4 Any (0.0.0.0) and IPv6 Any (::)

**Comment by Tragetaschen** [comment]
Binding to IPv6Any already binds to IPv4Any. Libuv is using dual stack sockets by default and needs an explicit bind flag to disable that.

**Comment by halter73** [comment]
@Tragetaschen Thanks for the heads up. It appears this only applies to IPv6Any. My testing shows that binding to IPv6Loopback does not bind to IPv4Loopback. Binding to IPv4Any also doesn't seem bind to IPv6Any.

**Comment by grahamehorner** [comment]
not sure if my experience is related to this issue; but I'm unable to get kestrel to listen on the hostname when the host has multiple network interfaces; even the localhost is unable to access the web application via the hostname; however localhost shows that kestrel is listening on the loopback interface.

**Comment by esko22** [comment]
Not sure if what I am seeing is also related but since switching to beta8 I have had a new issue pop up. Granted my use case is not common but I am running a Windows 10 VM on my Mac to host / debug my api host. Until switching to Beta8 I was able to make calls directly against the api hosted in the VM via port forwarding with no issues. 

The only way I can get this to work now is by launching Kestrel with the vm host name instead of localhost as I previously had in beta7. The odd thing is that on the Mac side I can make REST calls using either the vm host name or localhost and it resolves just fine. As soon as I try to host it on Kestrel with anything other then the VM host name the request times out with no error response.

**Comment by Tratcher** [comment]
@esko22 I think this is expected. Before beta8 kestrel would always listen publicly on Any/*, no matter what you specified. Now if you specify localhost it listens only on `::1`. As far as the VM is concerned the Mac is a separate machine so you need to listen on a public IP or *, not localhost.

**Comment by esko22** [comment]
Thanks @Tratcher. Using * works great.

**Comment by cesarbs** [comment]
Is this still an issue? Is there something to be fixed?

**Comment by Tratcher** [comment]
Yes, https://github.com/aspnet/KestrelHttpServer/pull/242#issuecomment-145688074

**Comment by DamianEdwards** [comment]
post RC2

**Comment by cesarbs** [comment]
I've published an announcement on this change: https://github.com/aspnet/Announcements/issues/185
