### ISSUE TITLE
SocketTransport rename ...

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/KestrelHttpServer#2487]
IMHO the SocketTransport should be renamed to TcpSocketTransport and implement the ITcpSocketTransport interface that is derived from the ISocketTransport, this would allow the registration of other types of transports including UdpSocketTransport IUdpSocketTransport by other server services and would avoid confusions around the type of Socket used by the SocketTransport factory etc.

**Comment by halter73** [comment]
This seems a little limiting IMHO. I don't see why the SocketTransport couldn't support UDP in the future if there was a desire for it.

**Comment by halter73** [comment]
Thinking about this a little more, I'm not sure UDP is the best example of an alternative protocol the SocketTransport could support because our transport abstraction expects a reliable data stream. It wouldn't be ideal to handle a connectionless protocol with our transport abstraction or with Pipelines in general for the same reason there isn't a UdpStream in .NET.

**Comment by davidfowl** [comment]
We should leave the name, the fact is it won't be TCP forever. We'll support any EndPoint type supported by sockets.
