### ISSUE TITLE
When the server aborts a connection any readers should get an OperationCanceled exception instead of an IOException

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#2546]
Sometimes when the connection is aborted by the server with the libuv transport, uv_write will fail with ECANCELED which will cause any attempt to read from the connection to throw an IOException instead of an OperationCanceledException like you would see from the Socket transport or even the libuv transport if the connection wasn't aborted mid-write.

**Comment by skyyark** [comment]
Hi.

I am running an AspNetCore Server (Kestrel + IIS) on Windows 2012 R2, and it started to produce this ECANCELED exception in the websocket receiveasync loop after upgrading to Core 2.0. Its websocket connections are supposed to stay alive for weeks. The problem is when this exception occurs, client-side websocket does not recognize that the connection has been lost, and the client does not run its reconnection logic. I am wondering why the server is producing ECANCELED exception and if it is normal and expected behavior. 

> System.IO.IOException: Error -4081 ECANCELED operation canceled ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled
   위치: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvOutputConsumer.<WriteOutputAsync>d__6.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection.<Start>d__26.MoveNext()
   --- 내부 예외 스택 추적의 끝 ---
   위치: Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
   위치: Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
   위치: Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
   위치: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<ReadAsync>d__22.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream.<ReadAsyncInternal>d__21.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<EnsureDataAvailableOrReadAsync>d__38.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<ReadNextFrameAsync>d__37.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<ReceiveAsync>d__36.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Spe.AspNetCore.WebSockets.WebSocketClient.<BeginReceive>d__22.MoveNext()
