### ISSUE TITLE
Support unix socket endpoint in ASPNETCORE_URLS

### ISSUE THREAD

**Issue by trondhindenes** [aspnet/KestrelHttpServer#2571]
As far as I can see, the ASPNETCORE_URLS environment variable only supports `http`-type endpoints.

Our developers are using Windows for local dev/debug, but we deploy to Linux. We'd like to be able to specify dynamically wether to use a http endpoint, a unix socket, or both. It looks like there's a bunch of code (wiring up `ListenUnixSocket`) that needs to be done in order for getting Kestrel to listen on Unix sockets.
The problem with this is that with the current option we have to do a bunch of if/then statement in order to dynamically build the correct listeners - IMHO it should simply be an environment variable or a list of appsettings.json settings. The "magical" `ASPNETCORE_URLS` should allow a semi-coloned list of listen endpoints and handle both http-type and socket-type endpoints.

**Comment by halter73** [comment]
Have you tried a URL like: `"http://unix:/path/to/unix.sock"` as seen [here](https://github.com/aspnet/KestrelHttpServer/blob/af636fc8d4870aeba5b892cdcd3994a5d956c475/test/Kestrel.Core.Tests/AddressBinderTests.cs#L80)? We generally recommend `ListenUnixSocket` since it doesn't have a weird syntax to remember, but the above seems like it would be easier for you.

I don't know what version of ASP.NET/Kestrel you're using, but keep in mind that the default transport is switch to managed Sockets in 2.1 while only the libuv transport currently supports Unix domain sockets. You can still [manually select the libuv transport](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&tabs=aspnetcore2x#transport-configuration) to continue using Unix domain sockets, and we [plan to add support](https://github.com/aspnet/KestrelHttpServer/issues/2156) for it to the managed Socket transport in the future.

**Comment by trondhindenes** [comment]
Thanks for the feedback. I didn't understand the second sentence at all, but I guess all I'm asking for is maybe clearer documentation around the unix socket hosting and configuration options. My test app is `netcoreapp2.0` using `AspNetCore 2.0.7`.

**Comment by halter73** [comment]
You don't have to worry about my second paragraph until you decide to upgrade to 2.1. For now, does using a url like `"http://unix:/path/to/unix.sock"` work for you? If so, we can move this issue over to https://github.com/aspnet/Docs/issues.

**Comment by trondhindenes** [comment]
Awesome :-). Yep, that seems to work!
