### ISSUE TITLE
HttpUpgradeStream doesn't have overloads for Memory<byte>

### ISSUE THREAD

**Issue by buybackoff** [aspnet/KestrelHttpServer#2620]
[HttpUpgradeStream](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Kestrel.Core/Internal/Http/HttpUpgradeStream.cs) was omitted from https://github.com/aspnet/KestrelHttpServer/pull/2333, while it's request and response streams do have those methods. Found it while investigating https://github.com/dotnet/corefx/issues/29951. 

Also cannot understand yet if the request and response streams use non-allocating ValueTask from https://github.com/dotnet/corefx/issues/27445?

So far all performance benefits from 2.1 are not available for WebSockets via `Microsoft.AspNetCore.WebSockets` middleware.

**Comment by davidfowl** [comment]
@muratg is this something we can patch in 2.1.1 as well? There's no public API change here fortunately.

**Comment by buybackoff** [comment]
Finally found your commit https://github.com/dotnet/corefx/commit/8958ef9a89f882886b233900b53788f13e6b0999 to understand if `HttpUpgradeStream` is the only blocker. And indeed it looks like a couple of `#ifdefs` should unlock the new `IValueTaskSource` feature.

**Comment by halter73** [comment]
> Also cannot understand yet if the request and response streams use non-allocating ValueTask from dotnet/corefx#27445?

For reads, we use the non-allocating ValueTask since it calls through to [MessageBody.ReadAsync](https://github.com/aspnet/KestrelHttpServer/blob/f80091a3280971977ec71711b9105f82d19e37f1/src/Kestrel.Core/Internal/Http/MessageBody.cs#L39) which awaits a `PipeReader` which in turn uses `ValueTask<TResult>` all the way through and saves an allocation in the event read data is already available at the time of the call.

For writes, it might look like we allocate a task since we call through the Task-returning [IHttpResponseControl.WriteAsync](https://github.com/aspnet/KestrelHttpServer/blob/f80091a3280971977ec71711b9105f82d19e37f1/src/Kestrel.Core/Internal/Http/IHttpResponseControl.cs#L13) method, but once again it doesn't allocate if the IO completes immediately (due to being able to fit in the `PipeWriter` buffer) due to [this trick](https://github.com/aspnet/KestrelHttpServer/blob/f80091a3280971977ec71711b9105f82d19e37f1/src/Kestrel.Core/Internal/Http/Http1OutputProducer.cs#L242) where we directly return `Task.CompletedTask`.

**Comment by buybackoff** [comment]
@halter73 yet on a synthetic test I see a lot allocations due to async machinery, and `Pipe.FlushAsync` is always on the path. Another huge source of allocations is ThreadPool, but `options.ApplicationSchedulingMode = SchedulingMode.Inline;` helps a lot in both allocations and throughput.

This picture below is for approximately 1 million messages sent from a single client: I fire 10 `WS.SendAsync` without awaiting, then await those 10 ValueTasks, then call `WS.ReadAsync` without awaiting and then await all 10. (the performance scales c.7 times from 1 task to 10 "concurrent" tasks). I could get c.86k messages per seconds in this benchmark with c.60% load of a core (on a 12 core machine, 5% of total). But adding 11th task throughput suddenly drops by 2+x . (A client build from `ClientWebSocket` on .NET 2.1. also has a similar picture - only async machinery allocates.)

Is it possible somehow to dedicate N threads for Send/Receive and do not use async machinery (e.g. like [NetMQ](https://github.com/zeromq/netmq) does)? Or too pool value Or somehow to avoid those noise allocations? Or I should choose something more specialized for this? (BTW, @davidfowl's [PlatformLevelTechempower](https://github.com/davidfowl/PlatformLevelTechempower) has exactly the same numbers +-jitter)

![image](https://user-images.githubusercontent.com/489852/40692321-bf65284c-63b9-11e8-81bf-0e73fe1f65df.png)

P.S. Haven't measured latency percentiles yet, but throughput is definitely enough my current task. I just love the middleware pipeline vs. manual sockets on a TCP port.

**Comment by halter73** [comment]
@buybackoff When IO is actually async (because read data is not yet available or the response buffers are full), seeing async allocations is completely expected. Since we don't want to block a thread, we have to move the continuation data off the stack and onto the heap.

**Comment by davidfowl** [comment]
> then call WS.ReadAsync without awaiting and then await all 10.

How does that even work, concurrent reads aren't supported. 

> (the performance scales c.7 times from 1 task to 10 "concurrent" tasks). I could get c.86k messages per seconds in this benchmark with c.60% load of a core (on a 12 core machine, 5% of total) 

I don't understand these numbers. What is c.7 and c.86k and c.60%? 

> But adding 11th task throughput suddenly drops by 2+x

Is that supposed to be 2x?

> Is it possible somehow to dedicate N threads for Send/Receive and do not use async machinery (e.g. like NetMQ does)? Or somehow to avoid those noise allocations?

If you use the libuv transport and the inline scheduling mode, you can run with a pure event loop model. Of course if you do anything to block the event loop you'll hurt performance. That in itself won't help avoid these allocations though as everything in the BCL and up stack from that use async/await internally and those continuations won't be scheduled on the event loop. I'm not convinced it's a better model anyways. The thread pool is very efficient and is really hard to beat in some cases.

> Or somehow to avoid those noise allocations? Or I should choose something more specialized for this? (BTW, @davidfowl's PlatformLevelTechempower has exactly the same numbers +-jitter)

Hard to know without understanding what you're trying to fix exactly. We try to reduce allocations where possible in the stack and it's very likely that we spent a small amount of time in the GC (you can look at this using a tool like perf view). I would focus on the per message allocations. Usually, if you can make the async state machine chunky (large long running async loops) then it's fine. The thing that ends up killing perf usually are short lived async state machines (the overhead of the async machinery might be too high for a short lived async method). This usually means receive loops are fine, but writing isn't. As @halter73 said, we return a completed task until you hit back pressure (the limit being configurable), but you might also be hitting asynchrony in the websocket layers itself (for example the fact that you're not awaiting means you're likely always hitting the slow async fallback path (https://github.com/dotnet/corefx/blob/dff80dc05a5d4f67fcef065aa9e625860ad71cd2/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L348).

> P.S. Haven't measured latency percentiles yet, but throughput is definitely enough my current task. I just love the middleware pipeline vs. manual sockets on a TCP port.

Let us know when you do.

> This exercise made crystal clear why Rust needed Pin<Self> to implement async/await. Basically Rust does forced GC0 per every call. Given that async/await is one of the main and powerful features of .NET it's interesting if garbage from async machinery could be put into a special "async object heap" (there is already LOH) and opposite to LOH, AOH could be cleared when every async state machine finishes...

This might be a better discussion to have on corefx or corclr (since it's GC related). There's been lots of improvements made to async/await in the library layers (amortized allocates trend towards 0 in .NET Core 2.1 https://github.com/dotnet/coreclr/pull/13105 and https://github.com/dotnet/coreclr/pull/14178) but there's always room for more.

**Comment by buybackoff** [comment]
> How does that even work, concurrent reads aren't supported.

It was a semaphore... 10 sends and then 10 receives. Measured wrong thing, just multiplexed messages. But at least that scales.

**Comment by halter73** [comment]
To expand on @davidfowl's point, while theoretically synchronous I/O could reduce async machinery related allocations at the cost of blocking threads (which use a lot of memory in their own right mostly for the stacks), this is not the case for ASP.NET since it written from the ground up using async/await meaning the async-related allocations will happen regardless.

When you use the synchronous Stream APIs with ASP.NET, you're basically adding hidden Task.Wait()s everywhere. We call this sync-over-async, and it gives you the worst of both worlds. In 2.0, we actually wanted to completely remove support for the synchronous Stream APIs in ASP.NET, but this broke too many things.

**Comment by buybackoff** [comment]
> Usually, if you can make the async state machine chunky (large long running async loops) then it's fine.

That is interesting, I did't quite realize that `while(true)` async loop is a single long-living state machine. Maybe be the simplest solution is to make write path fully async as the read path now?

@halter73 By synchronous I meant "avoid async machinery" and more like Libuv's event loop or SocketAsyncEventArgs but at higher level. Yet .NET's async machinery is very pleasant to work with and fast enough.
