### ISSUE TITLE
Consider running Mac OS tests serially instead of in parallel

### ISSUE THREAD

**Issue by muratg** [aspnet/KestrelHttpServer#2702]
Tests are flaky on Mac -- a lot more than Windows or Linux.

Our current thinking is that we may be hitting some resource limit on Mac and not other OSes. If this is true, running tests serially may help.

cc @halter73 @Tratcher @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Turns out we already do this. https://github.com/aspnet/KestrelHttpServer/blob/f7d459326c7ff5120c725e5da57c9d5cb30cd00c/test/Kestrel.FunctionalTests/Properties/AssemblyInfo.cs#L10-L12. We also avoid running libuv and sockets in parallel by creating a separate test group. Running tests in parallel is not likely the cause of the test flakiness.

**Comment by muratg** [comment]
Thanks for checking John.  

:
