### ISSUE TITLE
Limit size of memory buffer when reading request

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#304]
As @halter73 explained it to me, kestrel will constantly read the incoming request body off the socket and buffer it in memory until the application retrieves it. This could consume significant amounts of memory if the app isn't draining it fast enough.

Should Kestrel implement IHttpBufferingFeature.DisableRequestBuffering to stop preemptively buffering the request body and only read it on-demand? This would also let you put back-pressure on the client if they are sending data too quickly. This is also something that may make sense to enable/disable at startup.

**Comment by benaadams** [comment]
Or a `max buffered` property?

**Comment by muratg** [comment]
@cesarbs Feel free to ping @troydai as he has some context on this one.

**Comment by lodejard** [comment]
Having a max read-ahead would be a good idea. Disabling request buffering would be a different thing- that would be to stop the server or middleware from remembering the body, to disable "seek" rewinding

**Comment by DamianEdwards** [comment]
post RC2

**Comment by ChristineBoersen** [comment]
This is definitely an issue when sending an AJAX upload back to a controller with a **LARGE** file (hundreds of MB), as even if you use CopyToAsync to a filestream object, since the HttpContext.Request.Body stream was buffered, you run into an out of memory error. 

Is there a Kestrel Max Upload Size / Max Request Size equivalent to what used to be set in the web.config pre-kestrel that could be used as a workaround until this is resolved?

**Comment by muratg** [comment]
Thanks @mikeharder!
