### ISSUE TITLE
can not get remote ip addresss when using kestrel

### ISSUE THREAD

**Issue by guyajun0** [aspnet/KestrelHttpServer#359]
I Used asp.net 5, VS beta8 and dnx beta8 environment.
var remoteIp = context.Connection.RemoteIpAddress.ToString();

string remoteIp =context.Request.HttpContext.Features.Get<IHttpConnectionFeature>().RemoteIpAddress.ToString();

why the two method is always  getting null after I upgrade it from beta7 to beta8? Thank you!

when I use dnx beta7,it is ok to get the remote ip address,I am confused.

**Comment by Tratcher** [comment]
This was first Implemented for RC1. For beta7 you were probably used a different server by default (IIS/Helios?).

**Comment by Tratcher** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/67

**Comment by Tratcher** [comment]
Woops, RC2.

**Comment by troydai** [comment]
@guyajun0 would you please try out this scenario with the RC2 bits?

**Comment by NickCraver** [comment]
Semi-related: the exposed IPAddress is unaware of any proxy or load balancer - it's strictly reporting the endpoint...which confuses many developers the first time. The second stage of that is every app behind a load balancer implementing `X-Forwarded-Proto` and `X-Forwarded-For` with copy/paste code which is also often wrong or makes bad assumptions.

Is it worth discussing IP/Protocol handling having a future in an integrated way - whether in base Kestrel or another library? It's one of those things that would be much better off as an official and maintained library rather than something every major app has to implement themselves.

**Comment by Tratcher** [comment]
@NickCraver Yes, there's a middleware for that: https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNet.HttpOverrides/OverrideHeaderMiddleware.cs#L23

**Comment by guyajun0** [comment]
@troydai,Hi，Thank you for your attention,When I develop using kestrel and asp.net 5. "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8",this line should put in project.json, But the releases has no 1.0.0-rc2, The latest release is 1.0.0-beta8, How can I use 1.0.0-rc2 reference?

**Comment by shahid-pk** [comment]
@guyajun0 use **dnvm upgrade -u** . to get the latest unstable

**Comment by troydai** [comment]
@guyajun0 rc1 is just online. You can fetch the latest from nuget.org.

**Comment by troydai** [comment]
I'll close this issue.

**Comment by Tratcher** [comment]
e.g. dnvm upgrade

**Comment by guyajun0** [comment]
Thank you! As you say, RC1 can not get remote ip, So I have to wait your next release 1.0.0-RC2 to solve the problem. Waiting for your good news.

**Comment by txchen** [comment]
When will you release RC2?
This is a so basic scenario and I am shocked you don't cover this in your test. Insane!

**Comment by jasonwilliams200OK** [comment]
I share @txchen's anxiety. 

@troydai, @Tratcher, can this be backported to 'stable' rc1-updateX?  since by it looks 'stable' rc2 of `dotnet/<everything>` `aspnet/<everything>`  is at least weeks away due to the synchronized release cycles of all products (which should be strictly required for all repo/packages and this lack of asynchrony in release process is a pure limit on flexibility - cc releasemanagement folks)

**Comment by Tratcher** [comment]
@jasonwilliams200OK We have no plans to backport this. We haven't backported any RC2 changes to RC1 in any package. Releasing a backport would be more work logistically than finishing RC2 at this point.
