### ISSUE TITLE
If a ConnectionFilter throws asynchronously the connection is closed gracefully

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#368]
@Tratcher has found that if an HTTPS handshake fails the connection will be closed gracefully (i.e. a FIN will be sent) instead of being reset.

This is unexpected since `Connection.ConnectionControl.End(ProduceEndType.SocketDisconnect);` is called which should reset the connection. The only place the connection should ever be gracefully closed is at the end of `Frame.RequestProcessingAsync`.

**Comment by cesarbs** [comment]
The connection is not being reset because by the time the filter throws, all input has already been read (normally an RST would be sent if the connection was closed before all data was read). There's a way to force an RST (with high probability - but still not guaranteed) by setting `SO_LINGER` with a timeout of `0` on the socket, however libuv doesn't expose that.

Since this is not critical, I will close the issue.
