### ISSUE TITLE
[Documentation] Startup Exceptions may prevent SSL from being enabled

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#369]
SSL is enabled for kestrel via connection filters in Startup.Configure. `app.UseKestrelHttps(...);`  If an exception happens before this line in Startup then hosting will catch it, start the server, and display an http error page on that port. If an exception happens after that line then the error page will be served over https instead.

I'm filing this to document the odd behavior, I don't think we'd be able to fix it.

**Comment by NickCraver** [comment]
If we were using this in production and Startup failed for *any* reason, I'd much rather the server fail to start completely (e.g. process crash) and go to the logs to figure out why rather than have it partially functional in unexpected and less-likely-to-notice ways. 

Is it possible to completely bomb instead? I think most sysadmins would desire this behavior vs. a partial/unknown failure.

**Comment by muratg** [comment]
@glennc will look into documenting this behavior somewhere.

**Comment by DamianEdwards** [comment]
Didn't we change the Hosting behavior back to the app explicitly requiring an opt-in to capturing startup errors?

**Comment by Tratcher** [comment]
No, it's still opt-out.

**Comment by DamianEdwards** [comment]
OK. Given that in RC2 apps **have** to use the `WebHostBuilder` API directly, this can always be turned off by an app if desired. Let's ensure it's documented.

**Comment by muratg** [comment]
@danroth27 Could you track documentation here?

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/issues/1095
