### ISSUE TITLE
Set IO thread count to half of logical CPU count by default

### ISSUE THREAD

**Issue by AspNetSmurfLab** [aspnet/KestrelHttpServer#375]
Using an IO thread (libuv loop) for every 2 logical CPUs in the system appears to be a good default value based on benchmarking.

``` C#
IKestrelServerInformation.ThreadCount = Environment.ProcessorCount >> 1;
```

**Comment by NickCraver** [comment]
If this is a default, we may want a cap as well - starting next year we're talking 24+ cores per socket and I'd expect some decent falloff due to scheduler saturation. I'll be testing this on the Stack Overflow web tier in Colorado (our DR site) - there we're using dual E5-2690 v3 procs (24 physical cores total/48 logical) and see what load is like.  There's also some of our machine learning boxes on pairs of E5-2697v3 procs (28 physical cores/56 logical) I'll poke as well for reference.

If I can get the benchmarks setup next week, I'll try this across several servers. Related: the benchmark scripts for replication of the current numbers I'm seeing in PRs would be very beneficial in saving time here - left comments in that repo's issue list on it.

**Comment by muratg** [comment]
cc @lodejard let me know your thoughts, and we can set this (plus cap).

**Comment by benaadams** [comment]
PR: Network thread count defaults #378

**Comment by AspNetSmurfLab** [comment]
Thanks, would be great to see how this performs as we move up in core count.
