### ISSUE TITLE
CreateLinkedTokenSource is high alloc

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#407]
Using `CreateLinkedTokenSource` allocates more memory than the HttpContext! O_o

![Token source](http://aoa.blob.core.windows.net/aspnet/tokensource.png)

`_requestAbortCts = CancellationTokenSource.CreateLinkedTokenSource(_disconnectCts.Token);`

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L251

/cc @davidfowl @halter73

**Comment by khellang** [comment]
Precisely 40 bytes per request, I think? We had a bug with this in Nancy, where it wasn't disposed properly. Didn't work out well for memory usage :sob: 

![allocs](https://cloud.githubusercontent.com/assets/582487/11171766/a9337f1a-8bf8-11e5-845d-64bf69e91e63.png)

**Comment by benaadams** [comment]
They are being disposed ok; just bad for GC

**Comment by benaadams** [comment]
Also it the function takes a params[] so calling it allocates an array :-/

**Comment by NickCraver** [comment]
I don't see a clean way around this. There are *almost* enough bits exposed where this could be hoisted, but not quite:

```C#
private static readonly Action<object> _disconnectCtsAction = LinkedTokenCancelDelegate;
private static void LinkedTokenCancelDelegate(object source)
{
    CancellationTokenSource cts = source as CancellationTokenSource;
    Contract.Assert(source != null);
    cts.Cancel();
}
...
_disconnectCts.Token.Register(_disconnectCtsAction, _requestAbortCts);
```
The problem is there's no public API for excluding the execution context capture. If we had this exposed, it's duplicative of what CreateLinkedTokenSource is doing. On the other hand, we could eliminate several allocations here: the `params` and the internal `m_linkingRegistrations` registrations go away (since we have exactly one token and we can manually dispose the child).

I'm not sure if pursuing a new API on CancellationToken classes would go anywhere and it doesn't help the older platforms anyway...but should we? I can see this being a common pattern and there's a lot of overhead when we're talking about 2 tokens we have references to and can manually, directly dispose of.

**Comment by benaadams** [comment]
@NickCraver discussing over here https://github.com/dotnet/coreclr/issues/2113

**Comment by NickCraver** [comment]
Ah excellent - thanks @benaadams!

Unrelated but noticed when looking at allocations here: what is that `_nullBuffer` for?

**Comment by benaadams** [comment]
`_nullBuffer` is gone now, it was something to burn reads into in case the request hadn't been fully consumed. Now it fast forwards rather than actually reading.

**Comment by NickCraver** [comment]
@benaadams I could just be dense here, but where's the removal? I looked through current PRs and can't find any touching it - still seeing it in the dev branch.

**Comment by benaadams** [comment]
@NickCraver https://github.com/aspnet/KestrelHttpServer/pull/408 though it still allocates a CancellationTokenSource per request; just doesn't do the `CreateLinkedTokenSource` so its down quite a bit but not gone. Still a lot of stuff going on there:

![allocations](http://aoa.blob.core.windows.net/aspnet/allocations.png)

**Comment by NickCraver** [comment]
Hmm, I think we're talking about different things here (or at least, I see nothing related in #408) - I'm referring to line 35: https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L35

```C#
private readonly byte[] _nullBuffer = new byte[4096];
```

**Comment by benaadams** [comment]
Eeep! Good catch! It was meant to go as part of https://github.com/aspnet/KestrelHttpServer/pull/335 will submit a PR

**Comment by benaadams** [comment]
Is now in https://github.com/aspnet/KestrelHttpServer/pull/409

**Comment by NickCraver** [comment]
Okay awesome, thanks! I was in NYC this week but fly home from tomorrow; can't wait to test the latest over the weekend and hunt down remaining bottlenecks.

**Comment by mburbea** [comment]
I realize this was solved a different way, but why couldn't you call the overload that takes 2 CancellationTokenSources?
`_requestAbortCts = CancellationTokenSource.CreateLinkedTokenSource(_disconnectCts.Token, default(CancellationTokenSource);`

I'm fairly certain that since the default one is not cancellable this should at least avoid the array creation.

**Comment by benaadams** [comment]
@mburbea that's just twisted, though would likely work as is what `CancellationToken.None` is https://github.com/dotnet/coreclr/blob/0c298728a425b48c17b87f00211bd2bf368ec370/src/mscorlib/src/System/Threading/CancellationToken.cs#L61

**Comment by mburbea** [comment]
Err, it's been a while yeah `Default(CancellationToken)`. Yeah, it's a micro-op I've adopted in a few places. I use to use `new CancellationToken()`, but ever since C#6 allowed struct parameterless constructors i'm hesitant to use that form. 

It's not going to be the biggest win, but might cut your usage. 

How exactly does the pay for play get invoked? If I declare a method in a webapi that takes a CT do I have to pay the cost? In general, I feel like there's no reason not to use a CT in every place I can and I'm sure i'm not the only developer that feels that way.

**Comment by benaadams** [comment]
The CT is fine its the CTS that is expensive (well only 72 bytes.., now down to 64 bytes with some changes in coreclr). The pay for play means if nothing calls `Register` on the CT then the cost is not incurred; the cost itself only becomes an issue above 500k requests a second though; so I would worry too much :)
