### ISSUE TITLE
Add keep-alive timeout parameter

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#464]

**Comment by muratg** [comment]
Yeah, I think we should do this.  

cc @lodejard

**Comment by muratg** [comment]
@benaadams It looks like you're working on this.  Looking forward to see the PR!

**Comment by cesarbs** [comment]
@benaadams Are you working on this? I guess not since it's been 21 days since @muratg's comment :smile: I'll take this if no one's working on it.

**Comment by benaadams** [comment]
@cesarbs I was quite close with #485 though it needs rebasing; I can finish it of with improves if you can workout  #569? Haven't managed to work out what's going on there.

**Comment by cesarbs** [comment]
@benaadams I can't look into #569 immediately, so go ahead with #485 as it is right now.

**Comment by DamianEdwards** [comment]
post RC2

**Comment by darrelmiller** [comment]
It would be nice if this could be called "ConnectionTimeout" instead of Keep-Alive timeout.  IIS calls it [ConnectionTimeout](http://www.iis.net/configreference/system.applicationhost/sites/sitedefaults/limits).  By calling it Keep-Alive timeout there is an inference that is somehow related to the HTTP/1.0 extension `keep-alive` header and the [failed attempt to resurrect it for a different purpose.](https://tools.ietf.org/id/draft-thomson-hybi-http-timeout-01.html#rfc.section.2.1). 

Admittedly though, Apache does call it [KeepAliveTimeout](http://httpd.apache.org/docs/2.2/mod/core.html)

**Comment by cesarbs** [comment]
@darrelmiller It might happen https://github.com/aspnet/KestrelHttpServer/pull/1102 :smile:
