### ISSUE TITLE
Large number of 503s when running with more than 1000 virtual clients

### ISSUE THREAD

**Issue by SajayAntony** [aspnet/KestrelHttpServer#652]

**Comment by benaadams** [comment]
This behind reverse proxy? Don't think Kestrel itself currently returns a 503

Is middleware doing sync read/writes; json, or is it all async? (Or using `StreamSocketOutput.WriteAsync` https://github.com/aspnet/KestrelHttpServer/issues/569)

**Comment by SajayAntony** [comment]
@taoliseki could you describe the scenario more. Please add the description for how the connection density is being measured. Docs should be going to [stress location](https://github.com/aspnet/Performance/tree/dev/stress-test)

**Comment by taoliseki** [comment]
We were using 10k clients to load test a IIS hosted hello world MVC app. The 503s were caused by the default IIS config for "appConcurrentRequestLimit" setting. I increased that limit to increase server capacity (and was able to saturate the CPU):

https://technet.microsoft.com/en-us/library/dd425294(v=office.13).aspx

Note that we also need to increase the value for "MaxUserPort" registry, otherwise TCP ports needed for the communication between IIS and DNX will be exhausted, which will cause internal errors.
