### ISSUE TITLE
Kestrel as a library

### ISSUE THREAD

**Issue by VanCoding** [aspnet/KestrelHttpServer#664]
It seems that Kestrel is currently intended to be used as a standalone application, that hosts a DLL on a port specified by start parameters.

I'm wondering if there are plans to also create a good API to run kestrel inside of another application, maybe even multiple instances of it.

I imagine something very similar to node.js's http module. There you can:
```
http.createServer(function(req,res){
    res.end("Hello world!");
}).listen(80);
```
For Kestrel, this could look something like this:
```
var server = new KestrelServer(ctx => {
    await ctx.Response.Body.WriteAsync("Hello world!");
});
server.listen(80);
```

In my opinion, it'd be really cool to have Kestrel as an as easy as possible base for C# clones of for example express or koa.

**Comment by halter73** [comment]
You can achieve something very similar to this using, `WebHostBuilder`. This is the same type [used in the SampleApp](https://github.com/aspnet/KestrelHttpServer/blob/c7f64d34bbc2b8a3590660c40cd4dad36188b5b6/samples/SampleApp/Startup.cs#L66), but instead of using `UseStartup` you can call `Configure` like [we do in this hosting sample](https://github.com/aspnet/Hosting/blob/e62ceb852827d386b492abc9cc6801b1a8c70263/samples/SampleStartups/StartupFullControl.cs#L14). If you want a non-blocking version of `IWebHost.Run`, you can call `IWebHost.Start` like [we do in some of our tests](https://github.com/aspnet/KestrelHttpServer/blob/c7f64d34bbc2b8a3590660c40cd4dad36188b5b6/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/PathBaseTests.cs#L94). The linked test also shows a more minimal set of methods you can call to configure a web host.

**Comment by VanCoding** [comment]
Awesome, thank you :)
I'll try this as soon as I get one of the examples running.

**Comment by cesarbs** [comment]
Closing since there's no issue here and @VanCoding's scenario is supported as pointed out by @halter73.
