### ISSUE TITLE
HTTP Request Limits, Error On Huge (~50MB) File Uploads

### ISSUE THREAD

**Issue by Haplois** [aspnet/KestrelHttpServer#670]
I have an ASP .Net Core RC1 app hosted in Kestrel using IIS HttpPlatformHandler.  IIS Application Pool is configured not to run managed code, and web.config is below.

```
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="..\approot\web.cmd" arguments="" startupTimeLimit="3600" requestTimeout="00:10:00" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log" forwardWindowsAuthToken="false"></httpPlatform>
        <security>
            <requestFiltering>
                <requestLimits maxAllowedContentLength="62914560" />
            </requestFiltering>
        </security>
  </system.webServer>
</configuration>
```
 I also, enabled managed code, and tried 
```
    <system.web>
        <httpRuntime maxRequestLength="62914560" />
    </system.web>
```
with no luck.

I can't upload files bigger than 4MB. 

Am I missing some thing?

P.S. I don't have any special configuration for Kestrel command is registered directly like this:
```
    "commands": {
        "web": "Microsoft.AspNet.Server.Kestrel"
    },
```

**Comment by halter73** [comment]
Can you provide logs from your application when you try and fail to upload files? http://docs.asp.net/en/latest/fundamentals/logging.html

Did you notice any exceptions surfaced in your application code? When the client failed to complete the file upload was there any error message?

It's very possible that you are running into #520 which should be fixed in rc2, but I want to make sure.

**Comment by Haplois** [comment]
Thanks for your help @halter73, it seems that I was encountering that bug.
