### ISSUE TITLE
Chrome: net::ERR_INCOMPLETE_CHUNKED_ENCODING on first Razor page load

### ISSUE THREAD

**Issue by abrodersen** [aspnet/KestrelHttpServer#673]
Kestrel Version: `1.0.0-rc2-20051`
OS: `Windows 10 64-bit`

When issuing the first `GET /` after starting Kestrel, the Razor page is rendered as HTML correctly. However, the actual request fails in Chrome with the error `net::ERR_INCOMPLETE_CHUNKED_ENCODING`. Kestrel is using chunked encoding to send the response. The `Connection` header is set to `keep-alive`. Subsequent requests to the same resource succeed without issue.

According to Fiddler, the end of the on-the-wire response that fails looks like this:
````
</html>\r\n\r\n
````
or
````
3C 2F 68 74 6D 6C 3E 0D 0A 0D 0A
`````

The subsequent successful response looks like this:
````
</html>\r\n\r\n0\r\n\r\n
````
or
````
3C 2F 68 74 6D 6C 3E 0D 0A 0D 0A 30 0D 0A 0D 0A
````

It appears that the terminating chunk is missing in the first request. Is there any fix or work around for this?

**Comment by benaadams** [comment]
What version of Kestrel are you using?

**Comment by abrodersen** [comment]
1.0.0-rc2-20051

**Comment by halter73** [comment]
Were you able to reproduce this with one of your sample projects? If so, which one? If not, can you provide a sample that demonstrates this issue?

Kestrel has a few automated tests that verify that the first auto chunked response for a given connection properly ends with `0\r\n\r\n`.

Since you mentioned that it is the first request to a given resource, not the first request to a given connection, I quickly hit the home page of our [MusicStore sample](https://github.com/aspnet/MusicStore) (which uses Razor) running the latest bits to see if there is an issue higher up the stack. I also saw the proper chunked terminator there.

**Comment by muratg** [comment]
@abrodersen If you still have this issue, please either re-activate or file another issue with a minimal repro.

**Comment by halter73** [comment]
@abrodersen If you are running behind nginx you could be running into #406 If so, the workaround for rc1 is to add `proxy_http_version 1.1;` to your nginx config.

**Comment by shiza-arslan** [comment]
i passed the same url to postman and it gives me an actual result but when i send url from frontend it throw this error

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
