### ISSUE TITLE
Kestrel doesn't run when Webpack-dev-server is used with the Task Runner

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/KestrelHttpServer#729]
So I'm trying to get webpack to load up the dev-server (to get Hot module loading / etc going), and once that Task is "running" it basically stops the rest of the process. 

Not until that Task is stopped (pushing the X), then Kestrel web server finally opens up.

---------

*The long details:*

I have it loading up StaticFiles & DefaultFiles, all of that is working fine.

    app.UseDefaultFiles();
    app.UseStaticFiles();

Now the problem happens here, let's say I add the *npm script* `server:dev:hmr` to run **After Build**.

When running `web` (F5 / whatever), it starts running the script, loads up the webpack devServer, loads the modules, and then *STAYS* running. In which it never fires up the actual Kestrel server.

![image](https://cloud.githubusercontent.com/assets/2574412/14500522/72303092-0170-11e6-9ed6-c13896c408ef.png)

Now at this point if I load up localhost:5000 everything works, HMR, you name it. But of course Kestrel didn't boot up so the API or anything else doesn't.

If push that **X** in the corner and stop it, then... kestrel finally opens up, but at that point it's too late everything else is lost.

Any idea what could be causing this?

**Comment by cesarbs** [comment]
Are you using https://github.com/webpack/webpack-dev-server?

**Comment by cesarbs** [comment]
Can you share more details on how you're trying to run Kestrel via webpack?

**Comment by MarkPieszak** [comment]
Well right now I have the project opening `web` / kestrel instead of IIS Express.
Then in the Task Runner, I have it connected to an `npm script` "after build" that executes webpack:

    webpack --config config/webpack.dev.js --profile --hot

Which in turn fires up webpacks *devServer*

```
  devServer: {
    port: 3000, // doesn't matter if I change this to 5000 or anything
    host: 'localhost',
    historyApiFallback: true,
    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    }
  }
```

Basically it gets stuck right here ^.

In Task Runner it'll stay at "running" state, Kestrel never ends up Firing up. Once I close & stop this Task, then all of a sudden it fires up.

**Comment by halter73** [comment]
Are you running web.cmd produced by `dnu publish`? Does everything work as expected if you manually run web.cmd manually?

**Comment by MarkPieszak** [comment]
@halter73 Yes when I run `dnx web` from command line it's fine, or if I just **remove** the npm script that starts up *webpack & dev-server*. It's strange that the script stalls the entire process, almost as if it's hijacking it. Ideally I just want webpack's devServer (for the client-side) to run simultaneously with Kestrel (for the REST Web API). 

Have you guys had any luck with this at all?

**Comment by halter73** [comment]
I haven't tried the webpack dev server so I have no experience with this, but it seems unlikely to me that this is an issue with Kestrel given you description.

Are you sure that dnx is even running at all? If you replace `dnx web` with some other command, does that run?

**Comment by muratg** [comment]
Putting this in 1.0.0 for further discussion.

**Comment by spboyer** [comment]
@MarkPieszak try this solution

```
dnx web & webpack --config config/webpack.dev.js --profile --hot
```

I have a `dotnet cli` static server for Angular and run / live reload using nodemon see here

https://github.com/spboyer/ng2-kestrel-appserver/blob/master/package.json

**Comment by MarkPieszak** [comment]
@spboyer I'll give it a shot tomorrow morning! Thanks

**Comment by MarkPieszak** [comment]
@spboyer So what I have so far is that I've tried putting the repo [Angular2 Webpack starter](https://github.com/AngularClass/angular2-webpack-starter) into a blank .NET Core project.

I renamed wwwroot into what I needed / etc.

I have it loading up StaticFiles & DefaultFiles, all of that is working fine.

    app.UseDefaultFiles();
    app.UseStaticFiles();

Now the problem happens here, let's say I add the *npm script* `server:dev:hmr` to run **After Build**.

When running `web` (F5 / whatever), it starts running the script, loads up the webpack devServer, loads the modules, and then *STAYS* running. In which it never fires up the actual Kestrel server.

![image](https://cloud.githubusercontent.com/assets/2574412/14500522/72303092-0170-11e6-9ed6-c13896c408ef.png)

Now at this point if I load up localhost:5000 everything works, HMR, you name it. But of course Kestrel didn't boot up so the API or anything else doesn't.

If push that **X** in the corner and stop it, then... kestrel finally opens up, but at that point it's too late everything else is lost.

Am I missing something?

**Comment by spboyer** [comment]
@MarkPieszak Do you have a github repo for this so I/we can see the code? Would be easier to assist

**Comment by khellang** [comment]
So the issue is that DNX is waiting for your script to complete, but it never does because dev-server is blocking? Not sure if there's much to do about that.

**Comment by MarkPieszak** [comment]
@khellang Is there anyway to let it just open up Kestrel right away instead of waiting for the script to "finish"? Right now I basically am trying to get the script to run on Project open, that way Kestrel can open up on it's own.

@spboyer Making a github repo now, great idea

**Comment by khellang** [comment]
@MarkPieszak What do you mean you want to open up Kestrel right away? I think you're "abusing" the post-build script in order to do this. Those scripts are meant to do some work and finish in a timely manner, not start a HTTP server and block. I think you'd be better off just starting the dev-server from a separate console and keep the build scripts to... well, build stuff :wink:

**Comment by khellang** [comment]
@MarkPieszak This is basically why Kestrel (or the `dnx web` command) isn't executing; https://github.com/aspnet/dnx/blob/9de4ce9f45564621a432b4728a8787c0b53a0f03/src/Microsoft.Dnx.Tooling/Scripts/ScriptExecutor.cs#L120. DNX is shelling out to run the scripts you've specified, but since the dev-server is before `dnx web`, it's blocking and won't return an exit code. The same would be a problem if you switched the order of the commands. Then Kestrel would block and the dev-server wouldn't launch.

**Comment by MarkPieszak** [comment]
@khellang  Ahh there it is! That's the one doing it ;)
Is there a possibility to add a possibility to opt-out of that for certain tasks in the task-runner?

Yes it works if I do it separately I think I'll just have to stay with that path. Thank you though I guess that solves the problem since Kestrel is working as designed :(

**Comment by khellang** [comment]
@MarkPieszak Yeah, this certainly isn't a Kestrel issue. If anything, it's a DNX/DNU issue, but I don't think it matters much, since it's dead anyway :wink:

To be honest, I really don't think this is a "problem" you _want_ to solve. As I said; this is really abusing the script hooks of DNU. 

The script hooks are there so you can do a piece of work before or after some event and then exit; "move some files", "restore NPM modules", "run gulp", whatever. They're not designed to fire up stuff that'll never exit. What if the script failed? Has it finished yet? When do you go ahead with the next step in the build/pack/publish pipeline? You simply need the exit code in order to know whether it's "safe" to go ahead with the next step.

Also, say that you had fire-and-forget within scripts - would you want to? You realize that would mean that for each build, you would try to start a new dev-server, where each one but the first would fail to bind to the port because it's already in use?

**Comment by MarkPieszak** [comment]
Very very true. I'll have to rework my whole logic when trying to attach all of these processes with Kestrel and such. You're right at least now we know it's not a Kestrel issue I'll close out for now. Thanks for all the input and clarification though. 

After literally spending the past few days smashing my head against the desk trying to get all of this working I've realized that I definitely need to re-think it all. Haha

Thanks everyone for the feedback, I'll create a Repo of webpack / dev-server and everything working somewhat together once I *do* figure out some other solution. Just incase you all ever need a template project for it!

Cheers. :beers:
