### ISSUE TITLE
Kestrel listens on host:port instead of provided URI prefix

### ISSUE THREAD

**Issue by alecor191** [aspnet/KestrelHttpServer#834]
Hi,

I have a very simple ASP.NET Core RC2 app and I use the following code to configure the web host:

```csharp
var webHost = new WebHostBuilder()
    .UseContentRoot(Directory.GetCurrentDirectory())
    .UseStartup<Startup>()
    .UseKestrel()
    .UseUrls("http://localhost:5000/aspnetcorerc2/")
    .Build();

webHost.Run();
```

I.e. I would like Kestrel to listen on `http://localhost:5000/aspnetcorerc2/` (notice the path). The app works fine, however my app also serves requests sent to `http://localhost:5000/`. 

This is unexpected as I configured it explicitly to listen to the prefix including `/aspnetcorerc2/` path.

Am I doing something wrong in my configuration, or are there some limitations in Kestrel that would explain this behavior?

As I have multiple apps listening on the same port, I want to make sure that each uses a unique path so I need to make sure that Kestrel only listens to the configured prefix (and sub-paths).

I'm using version 1.0.0-rc2-16329.

**Comment by davidfowl** [comment]
You can't do this with Kestrel, it's an http.sys specific feature. You can only do it with WebListener not Kestrel.

**Comment by alecor191** [comment]
Thanks @davidfowl for clarifying!

**Comment by cesarbs** [comment]
@davidfowl You can do this in Kestrel :smile: 

@alecor191 This is by design. The path you add to the listen address will affect how `PathBase` is set in requests to your app. Requests to `/aspnetcorerc2/something` will have `PathBase` set to `/aspnetcorerc2` and `Path` set to `/something`. If your path base is not matched in a request, we made the decision to let your app do something about that instead of outright rejecting the request.

cc @Tratcher

**Comment by Tratcher** [comment]
But you still can't share the port.

**Comment by alecor191** [comment]
Thanks @cesarbs for clarifying. Unfortunately it doesn't help me in my scenario where I have two processes listening on the same port (different paths) as mentioned by @Tratcher. 

I'm using WebListener now as suggested by @davidfowl which works fine.
