### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object at .Kestrel.Infrastructure.Headers.Initialize

### ISSUE THREAD

**Issue by mnltejaswini** [aspnet/KestrelHttpServer#866]
I am running the following exception when running MusicStore app

```warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Server.Kestrel.Infrastructure.Headers.Initialize(DateHeaderValueManager dateValueManager)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Server.Kestrel.Infrastructure.Headers.Initialize(DateHeaderValueManager dateValueManager)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Server.Kestrel.Infrastructure.Headers.Initialize(DateHeaderValueManager dateValueManager)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()```

**Comment by rynowak** [comment]
We hit this today doing some perf testing with MusicStore. Seems to happen for the first few requests and then never again

**Comment by benaadams** [comment]
@halter73 in `DateHeaderManager`
`private volatile bool _hadRequestsSinceLastTimerTick = false;` 
should be 
`private volatile bool _hadRequestsSinceLastTimerTick = true;`
?

**Comment by benaadams** [comment]
@halter73 start-up race

In `DateHeaderManager`

`private volatile bool _hadRequestsSinceLastTimerTick = false;` 
should be 
`private volatile bool _hadRequestsSinceLastTimerTick = true;`

Or null test on

```
if (!_hadRequestsSinceLastTimerTick || _dateValues != null)
{
   PrepareDateValues();
}
```

First would be faster as second adds a test per request; but first isn't strictly true by variable name

**Comment by benaadams** [comment]
Start up race that seemed to work prior to https://github.com/aspnet/KestrelHttpServer/pull/810 by using an null array for the date header value which `FrameResponseHeaders.CopyTo` [would skip](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Http/FrameResponseHeaders.cs#L42) therefore not outputting a date header.

With the date bytes and date string now in a object; that object is null - which causes the null reference when resolving the bytes at start-up.

**Comment by halter73** [comment]
@benaadams This is a new race that didn't exists before #810.

First of all, `_dateBytes0` and `_dateBytes1` were never null, so `CopyToFast` doesn't influence this. Secondly, unlike now, the date byte array and string returned by `GetDateHeaderValue` and `GetDateHeaderValueBytes` were always initialized before they were returned.

Prior to #810, during timer startup, `GetDateHeaderValue` and `GetDateHeaderValueBytes` both would always called `PrepareDateValues`. If the timer hadn't started (as determined by`_timerIsRunning`) , `PrepareDateValues` would  call `StartTimer` which would only set `_timerIsRunning = true` *after* calling `SetDateValues(now);`.

Since #810 this logic is now flipped. Now instead of using `_timerIsRunning`, `GetDateHeaderValues` uses `_hadRequestsSinceLastTimerTick` to determine whether or not to call `StartTimer` in conjunction with checking `_timerIsRunning` in `PrepareDateValues` itself. Now this causes a race when first starting the timer because `_hadRequestsSinceLastTimerTick` is set to true *before* `_dateValues` is initialized which allows `GetDateHeaderValues` to return null on calls made quickly enough after the first one.

I think the fix is pretty simple: just go back to to always calling `StartTimer` iff  `_timerIsRunning` is false. Checking whether `_hadRequestsSinceLastTimerTick`is false in `GetDateHeaderValues` and only calling `PrepareDateValues` then makes no sense to me anyway. Previously `_hadRequestsSinceLastTimerTick` was *only* read to determine whether or not to update `_lastRequestSeenTicks`.

**Comment by sebastienros** [comment]
I approve this fix, good job guys. Let's fix all the race issues one at a time.
