### ISSUE TITLE
Azure hosting bug - The specified CGI application encountered an error and the server terminated the process.

### ISSUE THREAD

**Issue by xatabhk** [aspnet/KestrelHttpServer#939]
Azure site returns error message "The specified CGI application encountered an error and the server terminated the process." if SSL certificate is set in in Main() for Kestrel as follows: 
```
var application = new WebHostBuilder() ...
		.UseKestrel(options => { options.UseHttps("xxxx.pfx", "1xxxxx"); })
		.UseIISIntegration()
		.UseStartup<Startup>()
		.Build();
		application.Run();
```
![azure_ssl_error](https://cloud.githubusercontent.com/assets/6814395/16254368/c0efadec-3871-11e6-8921-532e9d22d8dc.png)

**Comment by davidfowl** [comment]
You can't use https on kestrel when hosted in front of IIS (which is how azure websites hosts you).

**Comment by xatabhk** [comment]
So how to detect if an app is hosted in front of IIS?

**Comment by GuardRex** [comment]
Maybe something like this?

```c#
KestrelServerOptions kestrelOptions = new KestrelServerOptions();
kestrelOptions.AddServerHeader = false;
kestrelOptions.<some_other_option> = <value>;
var pairingToken = Environment.GetEnvironmentVariable($"ASPNETCORE_TOKEN");
if (!string.IsNullOrEmpty(pairingToken))
{
    kestrelOptions.UseHttps("xxxx.pfx", "1xxxxx");
}
...
var host = new WebHostBuilder()
    .UseKestrel(kestrelOptions)

**Comment by Tratcher** [comment]
@halter73 this looks like a similar error to the other thread we saw. Have you been able to repro it to at least understand why it throws?

**Comment by davidfowl** [comment]
@xatabhk When are you not running behind IIS?

**Comment by cwe1ss** [comment]
> @xatabhk When are you not running behind IIS? 

obligatory "Azure Service Fabric" mention :laughing:

**Comment by xatabhk** [comment]
@davidfowl  I don't know actually. Behind IIS or not I see no difference in code.

**Comment by davidfowl** [comment]
Not sure what you mean. Do you have plans to run your program with just kestrel (btw that's not recommended for the public internet). If you're running behind IIS and I don't think you need to detect that, then you configure ssl there not in your application. 

If you plan to run on azure website then you're running on IIS and I'd recommend running IIS express locally (since your target is IIS)

**Comment by GuardRex** [comment]
@xatabhk 

> configure ssl there not in your application

https://azure.microsoft.com/en-us/documentation/articles/web-sites-configure-ssl-certificate/

**Comment by GuardRex** [comment]
@xatabhk Then you can use the code I posted above, which should detect running behind IIS based on the pairing token. In theory, that should work ... but @Tratcher and @davidfowl are the real experts here, so they'll give us the word on it.

**Comment by Tratcher** [comment]
@GuardRex Yes that should work, but I think your polarity is reversed:
```
if (string.IsNullOrEmpty(Environment.GetEnvironmentVariable($"ASPNETCORE_TOKEN")))
{
    kestrelOptions.UseHttps("xxxx.pfx", "1xxxxx");
}
```

That said, I'd still like to see the exception that's preventing it from working without this workaround.

**Comment by GuardRex** [comment]
Oooops! :smile: ... yeah ... cut-and-paste out of the repo code got me. Thx. It's fixed now.

**Comment by xatabhk** [comment]
@davidfowl Not planning, just doing tests and don't want to tie an app to IIS. Also no this issue with IIS Express in VS IDE.

**Comment by halter73** [comment]
@Tratcher I was able to successfully get Kestrel's sample app running  behind ANCM with `UseHttps`. It makes sense considering that the address provided by the module is HTTP, so the HTTPS connection filter isn't used.

@xatabhk Are you able to use HTTPS locally without IIS? Are you sure your publishing your pfx file to the correct location? If the pfx file isn't where the app expects you'll see an error like the following even at startup if HTTPS isn't used:

    Unhandled Exception: System.Security.Cryptography.CryptographicException: The system cannot find the file specified.
       at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
       at System.Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
       at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
       at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
       at Microsoft.AspNetCore.Hosting.KestrelServerOptionsHttpsExtensions.UseHttps(KestrelServerOptions options, String fileName, String password) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel.Https\KestrelServerOptionsHttpsExtensions.cs:line 51
       at SampleApp.Startup.<>c.<Main>b__1_0(KestrelServerOptions options) in C:\Users\shalter\dev\Universe\KestrelHttpServer\samples\SampleApp\Startup.cs:line 55

You could [enable stdout logging](https://docs.asp.net/en/latest/hosting/aspnet-core-module.html#log-creation-and-redirection) to try to see what error is happening. Make sure that the logging directory is published, because it will not be automatically created for you. You might also need to enable [console logging](https://docs.asp.net/en/latest/fundamentals/logging.html#configuring-logging-in-your-application) in your application.

**Comment by xatabhk** [comment]
@Tratcher @GuardRex Yes. The workaround works. But IIS Express does not need this workaround, so there may be a fix.

**Comment by xatabhk** [comment]
@halter73 Everything is OK locally, self-hosted or IIS Express hosted.

**Comment by benaadams** [comment]
> > > @xatabhk When are you not running behind IIS?

> > obligatory "Azure Service Fabric" mention :laughing:

> Not sure what you mean. Do you have plans to run your program with just kestrel (btw that's not recommended for the public internet).

I'd assume interconnected microservices that communicate directly with each other using Kestrel (either webapi or websockets) rather than a different network protocol (e.g. FabricTransport, Wcf, RabbitMQ, custom TCP etc).

If its an internet exposed cluster you would only have one gateway microservice exposed, which would be fronted by IIS (or multiple using hostname differentiation - which would also need IIS/http.sys); but you wouldn't use IIS as a layer between each microservice - however you may want to use https to secure the comms.
