### ISSUE TITLE
Implement chunked responses

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#97]
https://github.com/aspnet/KestrelHttpServer/issues/40

Currently Kestrel will read chunked requests, but it does not implement chunked responses. Instead it requires you to set the content-length or it will close the connection.

**Comment by Tratcher** [comment]
Enable this test when fixed:
https://github.com/aspnet/ServerTests/blob/dev/test/ServerComparison.FunctionalTests/ResponseTests.cs#L65

**Comment by halter73** [comment]
Currently you can write an application that writes chunked responses using kestrel as long as you manually add the "Transfer-Encoding: chunked" header and manually write out the number out the number of bytes in the next chunk to the response stream.

The purpose of this issue is the *default* to chunked responses if the "Content-Length" header isn't set by the application. Notice that the [web app being tested](https://github.com/aspnet/ServerTests/blob/a7a1ea59bfd1be60cb1b92dd64319272f0885e2c/test/ServerComparison.TestSites/StartupResponses.cs#L36) by the test @Tratcher suggests we enable once this issue is resolved does not explicitly set any headers. It simply calls WriteAsync and FlushAsync.

In this default scenario, Kestrel should set the "Transfer-Encoding: chunked" header automatically and use "Connection: keep-alive" header instead of the "Connection: close" header which will allow the client to reuse the same connection for multiple requests.

Most of the changes required for this change should be confined to the `Frame` class. `Frame.CreateResponseHeader` will definitely need to be changed. There will also need to be a change to `Frame.Write` to write out the number of bytes to be written before each chunk.

It's possible we can write out the number of bytes in `SocketOutput.Write` instead. This should allow us to write one chunk for each call `uv_write` instead of each call to `Frame.Write`, and there should be less calls to former with write behind buffering.
