### ISSUE TITLE
multiple slashes in URL causes 404?

### ISSUE THREAD

**Issue by UlyssesWu** [aspnet/KestrelHttpServer#980]
For a URL like `localhost:29559/api//auth/login`, IIS can handle it and turn the URL to `localhost:29559/api/auth/login`, but when in Kestrel (without IIS), it just return a 404 respone.

How to get Kestrel support mutiple slashes? I can not find any document about this. Thanks!

**Comment by Tratcher** [comment]
The only provision in the spec is that the path cannot start with double slashes. They're allowed after the first segment.
https://www.ietf.org/rfc/rfc3986.txt Section 3.3.
path-absolute   ; begins with "/" but not "//"
path-absolute = "/" [ segment-nz *( "/" segment ) ]
segment-nz    = 1*pchar
segment       = *pchar

It's unclear why IIS was consolidating these in the past. Maybe because it was a common developer mistake? I don't know why you would intentionally use double slash in your paths.

@ZestyBread Try writing a url-rewrite rule to clean this up.

**Comment by UlyssesWu** [comment]
@Tratcher Thanks for the reply. In fact I'm not using them "intentionally". It happens in this situation: 

Someone else is using this api:
```
//These api urls are got from a Json or something online
var apis = new string[]{ "xxx.com/api" , "yyy.com/api/" };
```

And he combines the urls with actions:
```
foreach(var api in apis)
{
    var url = string.Concat(api, "/auth/login");
    ...
}
```
He might thought it's alright to use `/auth/login` since it's appropriate for both api's urls(end with slash or without slash), or he just didn't know what would the urls be (and he was lazy). At this time the second url became `yyy.com/api//auth/login`. Most servers will handle it (nginx, IIS etc.), but not for Kestrel.

**Comment by mikeharder** [comment]
@rynowak, @Eilon: This might be something we'd want to address in Routing.

**Comment by Eilon** [comment]
@mikeharder I think the best place to address this is in a middleware that does URL rewriting, such as the one @ZestyBread is working on. We generally don't intend to mimic IIS's historical treatment of URLs, especially when it comes to attempts at canonicalization.
